#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v27
# autospec commit: cd8d006
#
Name     : dpcpp-compiler
Version  : 2025.06.06
Release  : 17
URL      : https://github.com/intel/llvm/archive/nightly-2025-06-06/llvm-2025-06-06.tar.gz
Source0  : https://github.com/intel/llvm/archive/nightly-2025-06-06/llvm-2025-06-06.tar.gz
Source1  : https://github.com/KhronosGroup/OpenCL-Headers/archive/v2024.10.24/OpenCL-Headers-2024.10.24.tar.gz
Source2  : https://github.com/KhronosGroup/OpenCL-ICD-Loader/archive/v2024.10.24/opencl-icd-loader-2024.10.24.tar.gz
Source3  : https://github.com/intel/compute-runtime/archive/refs/tags/25.09.32961.5.tar.gz
Source4  : https://github.com/ktprime/emhash/archive/a92897a9fa596e801cbafecd658ab0fd1b12e285.tar.gz
Source5  : https://github.com/uxlfoundation/oneapi-construction-kit/archive/v4.0.0/oneapi-construction-kit-4.0.0.tar.gz
Summary  : Unified Runtime Library Loader for Unified Runtime
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause CC0-1.0 MIT MPL-2.0 NCSA
Requires: dpcpp-compiler-bin = %{version}-%{release}
Requires: dpcpp-compiler-data = %{version}-%{release}
Requires: dpcpp-compiler-lib = %{version}-%{release}
Requires: dpcpp-compiler-license = %{version}-%{release}
BuildRequires : SPIRV-Headers-dev
BuildRequires : Vulkan-Headers-dev
BuildRequires : Vulkan-Loader-dev
BuildRequires : Vulkan-Tools
BuildRequires : Z3-dev
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : cmake
BuildRequires : curl-dev
BuildRequires : doxygen
BuildRequires : gcc-staticdev
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : glslang
BuildRequires : googletest-dev
BuildRequires : icu4c-dev
BuildRequires : level-zero-dev
BuildRequires : libbacktrace-staticdev
BuildRequires : libxml2-dev
BuildRequires : llvm-bin
BuildRequires : llvm-dev
BuildRequires : lua-dev
BuildRequires : ncurses-dev
BuildRequires : ninja
BuildRequires : perl
BuildRequires : pkg-config
BuildRequires : pkgconfig(LLVMSPIRVLib)
BuildRequires : pkgconfig(OpenCL-Headers)
BuildRequires : pkgconfig(SPIRV-Headers)
BuildRequires : pkgconfig(SPIRV-Tools)
BuildRequires : pkgconfig(level-zero)
BuildRequires : pkgconfig(libedit)
BuildRequires : pkgconfig(shaderc)
BuildRequires : protobuf-dev
BuildRequires : pypi(pybind11)
BuildRequires : python3-dev
BuildRequires : unified-memory-framework-dev
BuildRequires : vc-intrinsics-staticdev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Add-missing-sycl-include-path.patch
Patch2: 0002-Do-not-attempt-to-install-umf.patch

%description
Polly - Polyhedral optimizations for LLVM
-----------------------------------------
http://polly.llvm.org/

%package bin
Summary: bin components for the dpcpp-compiler package.
Group: Binaries
Requires: dpcpp-compiler-data = %{version}-%{release}
Requires: dpcpp-compiler-license = %{version}-%{release}

%description bin
bin components for the dpcpp-compiler package.


%package data
Summary: data components for the dpcpp-compiler package.
Group: Data

%description data
data components for the dpcpp-compiler package.


%package dev
Summary: dev components for the dpcpp-compiler package.
Group: Development
Requires: dpcpp-compiler-lib = %{version}-%{release}
Requires: dpcpp-compiler-bin = %{version}-%{release}
Requires: dpcpp-compiler-data = %{version}-%{release}
Provides: dpcpp-compiler-devel = %{version}-%{release}
Requires: dpcpp-compiler = %{version}-%{release}

%description dev
dev components for the dpcpp-compiler package.


%package lib
Summary: lib components for the dpcpp-compiler package.
Group: Libraries
Requires: dpcpp-compiler-data = %{version}-%{release}
Requires: dpcpp-compiler-license = %{version}-%{release}

%description lib
lib components for the dpcpp-compiler package.


%package license
Summary: license components for the dpcpp-compiler package.
Group: Default

%description license
license components for the dpcpp-compiler package.


%prep
%setup -q -n llvm-nightly-2025-06-06
cd %{_builddir}
tar xf %{_sourcedir}/OpenCL-Headers-2024.10.24.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/opencl-icd-loader-2024.10.24.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/oneapi-construction-kit-4.0.0.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/25.09.32961.5.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/a92897a9fa596e801cbafecd658ab0fd1b12e285.tar.gz
cd %{_builddir}/llvm-nightly-2025-06-06
mkdir -p ../opencl-headers
cp -r %{_builddir}/OpenCL-Headers-2024.10.24/. %{_builddir}/llvm-nightly-2025-06-06/../opencl-headers
mkdir -p ../ocl-icd-src
cp -r %{_builddir}/OpenCL-ICD-Loader-2024.10.24/. %{_builddir}/llvm-nightly-2025-06-06/../ocl-icd-src
mkdir -p ../oneapi-construction-kit
cp -r %{_builddir}/oneapi-construction-kit-4.0.0/. %{_builddir}/llvm-nightly-2025-06-06/../oneapi-construction-kit
mkdir -p ../compute-runtime
cp -r %{_builddir}/compute-runtime-25.09.32961.5/. %{_builddir}/llvm-nightly-2025-06-06/../compute-runtime
mkdir -p ../emhash
cp -r %{_builddir}/emhash-a92897a9fa596e801cbafecd658ab0fd1b12e285/. %{_builddir}/llvm-nightly-2025-06-06/../emhash
%patch -P 1 -p1
%patch -P 2 -p1

%build
## build_prepend content
CXXFLAGS="${CXXFLAGS} -fpermissive"
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1750109229
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ../llvm -DBUG_REPORT_URL=https://github.com/intel/llvm/issues \
-DCMAKE_VERBOSE_MAKEFILE=ON \
-DCOMPUTE_RUNTIME_LEVEL_ZERO_INCLUDE=%{_builddir}/compute-runtime/level_zero/include/ \
-DEMHASH_SYS_LOC=%{_builddir}/emhash \
-DFETCHCONTENT_FULLY_DISCONNECTED=ON \
-DFETCHCONTENT_SOURCE_DIR_OCL-HEADERS=%{_builddir}/opencl-headers \
-DFETCHCONTENT_SOURCE_DIR_OCL-ICD=%{_builddir}/ocl-icd-src \
-DLIBCLC_GENERATE_REMANGLED_VARIANTS=OFF \
-DLIBCLC_TARGETS_TO_BUILD= \
-DLLVM_BUILD_TOOLS=ON \
-DLLVM_ENABLE_PROJECTS='clang;sycl;llvm-spirv;libdevice;opencl' \
-DLLVM_ENABLE_ZSTD=OFF \
-DLLVM_EXTERNAL_LIBDEVICE_SOURCE_DIR=../libdevice \
-DLLVM_EXTERNAL_LLVM_SPIRV_SOURCE_DIR=../llvm-spirv \
-DLLVM_EXTERNAL_PROJECTS='sycl;llvm-spirv;libdevice;opencl' \
-DLLVM_EXTERNAL_SPIRV_HEADERS_SOURCE_DIR=/usr/include/spirv \
-DLLVM_EXTERNAL_SYCL_SOURCE_DIR=../sycl \
-DLLVM_LIBDIR_SUFFIX=64 \
-DLLVM_TARGETS_TO_BUILD=X86 \
-DLLVM_USE_STATIC_ZSTD=OFF \
-DLLVM_VERSION_SUFFIX=-dpcpp \
-DOpenCL_INCLUDE_DIR=/usr/include \
-DSYCL_CLANG_EXTRA_FLAGS='-Isycl/include' \
-DSYCL_ENABLE_BACKENDS='level_zero;level_zero_v2' \
-DSYCL_ENABLE_EXTENSION_JIT=OFF \
-DSYCL_ENABLE_WERROR=OFF \
-DSYCL_INCLUDE_TESTS=ON \
-DSYCL_LIBDEVICE_GCC_TOOLCHAIN=/usr/lib64/gcc/x86_64-generic-linux/15 \
-DUR_COMPUTE_RUNTIME_FETCH_REPO=OFF \
-DUR_COMPUTE_RUNTIME_REPO=%{_builddir}/compute-runtime \
-DUR_ENABLE_TRACING=OFF \
-DUR_LEVEL_ZERO_INCLUDE_DIR=/usr/include/level_zero \
-DUR_LEVEL_ZERO_LOADER_LIBRARY=/lib64/libze_loader.so.1 \
-DUR_USE_EXTERNAL_UMF=ON \
-DBUILD_SHARED_LIBS:BOOL=OFF \
-DLLVM_ENABLE_RTTI:BOOL=ON \
-DLLVM_REQUIRES_RTTI:BOOL=ON  -G Ninja
ninja  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1750109229
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/dpcpp-compiler
cp %{_builddir}/OpenCL-Headers-2024.10.24/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/OpenCL-ICD-Loader-2024.10.24/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/compute-runtime-25.09.32961.5/LICENSE.md %{buildroot}/usr/share/package-licenses/dpcpp-compiler/364c81eae824ba65626c2442274579712dc24708 || :
cp %{_builddir}/compute-runtime-25.09.32961.5/scripts/packaging/l0_gpu_driver/rhel_8/copyright %{buildroot}/usr/share/package-licenses/dpcpp-compiler/205f35d8fa25bc2a6d6d9eb79eb06d4fb33d9be4 || :
cp %{_builddir}/compute-runtime-25.09.32961.5/scripts/packaging/l0_gpu_driver/sles_15/copyright %{buildroot}/usr/share/package-licenses/dpcpp-compiler/205f35d8fa25bc2a6d6d9eb79eb06d4fb33d9be4 || :
cp %{_builddir}/compute-runtime-25.09.32961.5/scripts/packaging/l0_gpu_driver/ubuntu_20.04/copyright %{buildroot}/usr/share/package-licenses/dpcpp-compiler/d255f01e9636b0346a9650d2ba50692a03e8938e || :
cp %{_builddir}/compute-runtime-25.09.32961.5/scripts/packaging/opencl/rhel_8/copyright %{buildroot}/usr/share/package-licenses/dpcpp-compiler/d5c5d1f2a2c34ddf445bd787517a4423a2fd5b1b || :
cp %{_builddir}/compute-runtime-25.09.32961.5/scripts/packaging/opencl/sles_15/copyright %{buildroot}/usr/share/package-licenses/dpcpp-compiler/d5c5d1f2a2c34ddf445bd787517a4423a2fd5b1b || :
cp %{_builddir}/compute-runtime-25.09.32961.5/scripts/packaging/opencl/ubuntu_20.04/copyright %{buildroot}/usr/share/package-licenses/dpcpp-compiler/512260ce8ee598c5985f35ea4d8834e6c35f4958 || :
cp %{_builddir}/compute-runtime-25.09.32961.5/scripts/packaging/ubuntu/copyright %{buildroot}/usr/share/package-licenses/dpcpp-compiler/512260ce8ee598c5985f35ea4d8834e6c35f4958 || :
cp %{_builddir}/compute-runtime-25.09.32961.5/third_party/DirectX-Headers/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/5d941660d20397d61e58adb87e2dd05fa60828ef || :
cp %{_builddir}/compute-runtime-25.09.32961.5/third_party/gtest/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/5a2314153eadadc69258a9429104cd11804ea304 || :
cp %{_builddir}/compute-runtime-25.09.32961.5/third_party/libdxg/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/compute-runtime-25.09.32961.5/third_party/metrics_discovery/LICENSE.md %{buildroot}/usr/share/package-licenses/dpcpp-compiler/24ebc22b6e51adf8b01ec0340b69fc7dd2178c1d || :
cp %{_builddir}/compute-runtime-25.09.32961.5/third_party/metrics_library/LICENSE.md %{buildroot}/usr/share/package-licenses/dpcpp-compiler/1020f0e93b771814d86731da816eb9f22f2ab7b4 || :
cp %{_builddir}/compute-runtime-25.09.32961.5/third_party/opencl_headers/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compute-runtime-25.09.32961.5/third_party/sse2neon/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/218fc8c15534e8840cbff5801582c450c97869ab || :
cp %{_builddir}/emhash-a92897a9fa596e801cbafecd658ab0fd1b12e285/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/833029af4fec08f548eee8861ee73e8ef9395b2b || :
cp %{_builddir}/emhash-a92897a9fa596e801cbafecd658ab0fd1b12e285/thirdparty/simd_hash_map/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/7bb7e3e90405caf5d2dfb4bc5c9a4e52c836d66d || :
cp %{_builddir}/llvm-nightly-2025-06-06/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/af07f365643f841c69797e9059b66f0bd847f1cd || :
cp %{_builddir}/llvm-nightly-2025-06-06/bolt/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/af07f365643f841c69797e9059b66f0bd847f1cd || :
cp %{_builddir}/llvm-nightly-2025-06-06/clang-tools-extra/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/a1691103171dc1d21cfa85f1d4809a16b9f1367f || :
cp %{_builddir}/llvm-nightly-2025-06-06/clang/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/a1691103171dc1d21cfa85f1d4809a16b9f1367f || :
cp %{_builddir}/llvm-nightly-2025-06-06/compiler-rt/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/f4359b9da55a3b9e4d9513eb79cacf125fb49e7b || :
cp %{_builddir}/llvm-nightly-2025-06-06/cross-project-tests/debuginfo-tests/dexter/LICENSE.txt %{buildroot}/usr/share/package-licenses/dpcpp-compiler/af07f365643f841c69797e9059b66f0bd847f1cd || :
cp %{_builddir}/llvm-nightly-2025-06-06/flang-rt/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/85c0f2884378413881b4d3e27fc24b220f71889b || :
cp %{_builddir}/llvm-nightly-2025-06-06/flang/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/85c0f2884378413881b4d3e27fc24b220f71889b || :
cp %{_builddir}/llvm-nightly-2025-06-06/libc/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/a1691103171dc1d21cfa85f1d4809a16b9f1367f || :
cp %{_builddir}/llvm-nightly-2025-06-06/libclc/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/8737af83de0d40386dca9a4abe2b6faa83cb4750 || :
cp %{_builddir}/llvm-nightly-2025-06-06/libcxx/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/7b75a5471af8b3d49e60df0a5d72f95ea8214231 || :
cp %{_builddir}/llvm-nightly-2025-06-06/libcxxabi/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/11156021d878bfcbdf2563b4f65db32b4d9f92a3 || :
cp %{_builddir}/llvm-nightly-2025-06-06/libunwind/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/d79062af10a33188d4a74d976323845a2cf9023d || :
cp %{_builddir}/llvm-nightly-2025-06-06/lld/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/6b655b0685aa7ee33fa1e02103b3bf22ed06e099 || :
cp %{_builddir}/llvm-nightly-2025-06-06/lldb/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/8af372ad1edbed2cfaf0e79d25f7136ec6e55b47 || :
cp %{_builddir}/llvm-nightly-2025-06-06/lldb/tools/lldb-dap/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/85c0f2884378413881b4d3e27fc24b220f71889b || :
cp %{_builddir}/llvm-nightly-2025-06-06/llvm-spirv/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/8f178caf2a2d6e6c711a30da69077572df356cf6 || :
cp %{_builddir}/llvm-nightly-2025-06-06/llvm/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/af07f365643f841c69797e9059b66f0bd847f1cd || :
cp %{_builddir}/llvm-nightly-2025-06-06/llvm/include/llvm/Support/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/5feeec1755c1a12a9ade79c0db7ce0dd05baf119 || :
cp %{_builddir}/llvm-nightly-2025-06-06/llvm/lib/Support/BLAKE3/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/bfc2b026231b7aca6db90de3471e76dbb94e9c24 || :
cp %{_builddir}/llvm-nightly-2025-06-06/llvm/test/YAMLParser/LICENSE.txt %{buildroot}/usr/share/package-licenses/dpcpp-compiler/c01c212bdf3925189f673e2081b44094023860ea || :
cp %{_builddir}/llvm-nightly-2025-06-06/llvm/utils/lit/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/af07f365643f841c69797e9059b66f0bd847f1cd || :
cp %{_builddir}/llvm-nightly-2025-06-06/mlir/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/85c0f2884378413881b4d3e27fc24b220f71889b || :
cp %{_builddir}/llvm-nightly-2025-06-06/openmp/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/e3cccabb67bd491a643d32a7d2b65b49836e626d || :
cp %{_builddir}/llvm-nightly-2025-06-06/openmp/runtime/src/thirdparty/ittnotify/LICENSE.txt %{buildroot}/usr/share/package-licenses/dpcpp-compiler/59a8ba331dede4d94bd654ac645e8d27463662f4 || :
cp %{_builddir}/llvm-nightly-2025-06-06/polly/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/8d3b142938f83e7045951089b52676a5605eee37 || :
cp %{_builddir}/llvm-nightly-2025-06-06/polly/lib/External/isl/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/45c2429b5881295597e96c81fc50f7b8a42e769f || :
cp %{_builddir}/llvm-nightly-2025-06-06/polly/lib/External/isl/imath/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/385649e7c18da3a07cfbd6679eebd0bca1c698c9 || :
cp %{_builddir}/llvm-nightly-2025-06-06/pstl/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/72c865be698cefc46549ed61e279f98432364fca || :
cp %{_builddir}/llvm-nightly-2025-06-06/sycl/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/2858f1aaa0df159c19da9047793c176ded5fde73 || :
cp %{_builddir}/llvm-nightly-2025-06-06/third-party/benchmark/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/llvm-nightly-2025-06-06/third-party/unittest/googlemock/LICENSE.txt %{buildroot}/usr/share/package-licenses/dpcpp-compiler/5a2314153eadadc69258a9429104cd11804ea304 || :
cp %{_builddir}/llvm-nightly-2025-06-06/third-party/unittest/googletest/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/5a2314153eadadc69258a9429104cd11804ea304 || :
cp %{_builddir}/llvm-nightly-2025-06-06/unified-runtime/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/5a64e4783751612e7603131e11bb81655bcb2b4e || :
cp %{_builddir}/llvm-nightly-2025-06-06/xptifw/basic_test/external/LICENSE.txt %{buildroot}/usr/share/package-licenses/dpcpp-compiler/5ffa2266f82fe7453a84cc81e06ef01fa4b451d5 || :
cp %{_builddir}/oneapi-construction-kit-4.0.0/LICENSE.txt %{buildroot}/usr/share/package-licenses/dpcpp-compiler/7e042c41bcb0960a16525d88d8308cf7ee444463 || :
cp %{_builddir}/oneapi-construction-kit-4.0.0/clik/examples/option_parser/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/a6695de026d58b7d5759b497587ccc941f90e991 || :
cp %{_builddir}/oneapi-construction-kit-4.0.0/examples/refsi/hal_refsi/external/refsidrv/LICENSE.spike %{buildroot}/usr/share/package-licenses/dpcpp-compiler/069917c4e281e9c890d84d0e4c081e295741a146 || :
cp %{_builddir}/oneapi-construction-kit-4.0.0/examples/refsi/hal_refsi/source/loader/LICENSE.spike %{buildroot}/usr/share/package-licenses/dpcpp-compiler/069917c4e281e9c890d84d0e4c081e295741a146 || :
cp %{_builddir}/oneapi-construction-kit-4.0.0/external/benchmark/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/oneapi-construction-kit-4.0.0/external/googletest/LICENSE.txt %{buildroot}/usr/share/package-licenses/dpcpp-compiler/5a2314153eadadc69258a9429104cd11804ea304 || :
cp %{_builddir}/oneapi-construction-kit-4.0.0/modules/cargo/LICENSE.txt %{buildroot}/usr/share/package-licenses/dpcpp-compiler/0884cb5458dcea3aeca8bf62ff4638f145da9080 || :
cp %{_builddir}/oneapi-construction-kit-4.0.0/modules/cargo/expected.LICENSE.txt %{buildroot}/usr/share/package-licenses/dpcpp-compiler/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/oneapi-construction-kit-4.0.0/modules/cargo/function_ref.LICENSE.txt %{buildroot}/usr/share/package-licenses/dpcpp-compiler/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/oneapi-construction-kit-4.0.0/modules/cargo/optional.LICENSE.txt %{buildroot}/usr/share/package-licenses/dpcpp-compiler/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/oneapi-construction-kit-4.0.0/modules/compiler/builtins/abacus/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/fccfc2fce8f47edefc797bdc3835ddd9a614ccd5 || :
cp %{_builddir}/oneapi-construction-kit-4.0.0/modules/compiler/vecz/LICENSE.txt %{buildroot}/usr/share/package-licenses/dpcpp-compiler/38c74b79370d3a6a99c7b80c3d48e6caaf0636f2 || :
cp %{_builddir}/oneapi-construction-kit-4.0.0/modules/mux/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/b52b5d7278f63f47262b5cbf5ae7762073bbf885 || :
cp %{_builddir}/oneapi-construction-kit-4.0.0/modules/mux/targets/host/test/lit/LICENSE.txt %{buildroot}/usr/share/package-licenses/dpcpp-compiler/e296859078301a417e5364eac616b0ec020d088a || :
cp %{_builddir}/oneapi-construction-kit-4.0.0/source/cl/test/BenchCL/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/19ab4d0ca881c5cb0eb16b70c76c89d854aa291e || :
cp %{_builddir}/oneapi-construction-kit-4.0.0/source/vk/external/Khronos/LICENSE.txt %{buildroot}/usr/share/package-licenses/dpcpp-compiler/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%ninja_install
popd
## Remove excluded files
rm -f %{buildroot}*/usr/include/clang/AST/SYCLKernelInfo.h
rm -f %{buildroot}*/usr/include/clang/AST/StmtSYCL.h
rm -f %{buildroot}*/usr/include/clang/Sema/SemaSYCL.h
rm -f %{buildroot}*/usr/lib/libLTO.so
rm -f %{buildroot}*/usr/lib/libRemarks.so
rm -f %{buildroot}*/usr/lib/libclang-cpp.so
rm -f %{buildroot}*/usr/lib/libclang.so
rm -f %{buildroot}*/usr/lib64/cmake/clang/*
rm -f %{buildroot}*/usr/lib64/cmake/llvm/*
rm -f %{buildroot}*/usr/lib64/libLTO.so
rm -f %{buildroot}*/usr/lib64/libRemarks.so
rm -f %{buildroot}*/usr/lib64/libclang-cpp.so
rm -f %{buildroot}*/usr/lib64/libclang.so
rm -f %{buildroot}*/usr/lib64/pkgconfig/LLVMSPIRVLib.pc
rm -f %{buildroot}*/usr/libexec/analyze-c++
rm -f %{buildroot}*/usr/libexec/analyze-cc
rm -f %{buildroot}*/usr/libexec/c++-analyzer
rm -f %{buildroot}*/usr/libexec/ccc-analyzer
rm -f %{buildroot}*/usr/libexec/intercept-c++
rm -f %{buildroot}*/usr/libexec/intercept-cc
rm -f %{buildroot}*/usr/share/clang/bash-autocomplete.sh
rm -f %{buildroot}*/usr/share/clang/clang-format-bbedit.applescript
rm -f %{buildroot}*/usr/share/clang/clang-format-diff.py
rm -f %{buildroot}*/usr/share/clang/clang-format-sublime.py
rm -f %{buildroot}*/usr/share/clang/clang-format.el
rm -f %{buildroot}*/usr/share/clang/clang-format.py
rm -f %{buildroot}*/usr/share/clang/clang-rename.el
rm -f %{buildroot}*/usr/share/clang/clang-rename.py
rm -f %{buildroot}*/usr/share/man/man1/scan-build.1
rm -f %{buildroot}*/usr/share/opt-viewer/opt-diff.py
rm -f %{buildroot}*/usr/share/opt-viewer/opt-stats.py
rm -f %{buildroot}*/usr/share/opt-viewer/opt-viewer.py
rm -f %{buildroot}*/usr/share/opt-viewer/optpmap.py
rm -f %{buildroot}*/usr/share/opt-viewer/optrecord.py
rm -f %{buildroot}*/usr/share/opt-viewer/style.css
rm -f %{buildroot}*/usr/share/scan-build/scanview.css
rm -f %{buildroot}*/usr/share/scan-build/sorttable.js
rm -f %{buildroot}*/usr/share/scan-view/Reporter.py
rm -f %{buildroot}*/usr/share/scan-view/ScanView.py
rm -f %{buildroot}*/usr/share/scan-view/bugcatcher.ico
rm -f %{buildroot}*/usr/share/scan-view/startfile.py
rm -f %{buildroot}*/usr/lib64/libOpenCL.so*
rm -f %{buildroot}*/usr/lib64/pkgconfig/OpenCL.pc
rm -f %{buildroot}*/usr/include/CL/cl.h
rm -f %{buildroot}*/usr/include/CL/cl_d3d10.h
rm -f %{buildroot}*/usr/include/CL/cl_d3d11.h
rm -f %{buildroot}*/usr/include/CL/cl_dx9_media_sharing.h
rm -f %{buildroot}*/usr/include/CL/cl_dx9_media_sharing_intel.h
rm -f %{buildroot}*/usr/include/CL/cl_egl.h
rm -f %{buildroot}*/usr/include/CL/cl_ext.h
rm -f %{buildroot}*/usr/include/CL/cl_ext_intel.h
rm -f %{buildroot}*/usr/include/CL/cl_gl.h
rm -f %{buildroot}*/usr/include/CL/cl_gl_ext.h
rm -f %{buildroot}*/usr/include/CL/cl_half.h
rm -f %{buildroot}*/usr/include/CL/cl_half.h
rm -f %{buildroot}*/usr/include/CL/cl_icd.h
rm -f %{buildroot}*/usr/include/CL/cl_layer.h
rm -f %{buildroot}*/usr/include/CL/cl_platform.h
rm -f %{buildroot}*/usr/include/CL/cl_va_api_media_sharing_intel.h
rm -f %{buildroot}*/usr/include/CL/cl_version.h
rm -f %{buildroot}*/usr/include/CL/opencl.h
rm -f %{buildroot}*/usr/lib64/pkgconfig/OpenCL-Headers.pc
rm -f %{buildroot}*/usr/share/cmake/OpenCLHeaders/OpenCLHeadersConfig.cmake
rm -f %{buildroot}*/usr/share/cmake/OpenCLHeaders/OpenCLHeadersConfigVersion.cmake
rm -f %{buildroot}*/usr/share/cmake/OpenCLHeaders/OpenCLHeadersTargets.cmake
## install_append content
# remove libomptarget.rtl.amdgpu.so for now
# it is built using rpath and wants to be in the wrong path
# rm -f %{buildroot}/usr/lib/libomptarget.rtl.amdgpu.so

# Remove files that should come from the main llvm package
# rm -rf %{buildroot}/usr/include
# rm -rf %{buildroot}/usr/lib/python3.11
# rm -rf %{buildroot}/usr/lib32/*.a
# rm -rf %{buildroot}/usr/lib32/*.so
# rm -rf %{buildroot}/usr/lib32/cmake
# rm -rf %{buildroot}/usr/lib32/pkgconfig
# rm -rf %{buildroot}/usr/lib64/*.a
# rm -rf %{buildroot}/usr/lib64/*.so
# rm -rf %{buildroot}/usr/lib64/cmake
# rm -rf %{buildroot}/usr/lib64/pkgconfig
# rm -rf %{buildroot}/usr/libexec

# Remove things we shouldn't be providing in the first place
rm -rf %{buildroot}/usr/lib/libear
rm -rf %{buildroot}/usr/lib/libscanbuild

# Remove all the includes *except* those for SYCL
find %{buildroot}/usr/include '(' -type f -a '!' -ipath '*sycl*' ')' -exec rm {} +

# Cleanup empty directories
find %{buildroot}/usr/include -type d -empty -exec rmdir {} +

# mv %{buildroot}/usr/share/package-licenses %{buildroot}/usr/
# rm -rf %{buildroot}/usr/share/*
# mv %{buildroot}/usr/package-licenses %{buildroot}/usr/share

# Rename the tools to have a versioned suffix and symlink back
pushd %{buildroot}/usr
VARIANT_TAG=dpcpp
mkdir -p lib64/clang/$VARIANT_TAG/bin
mv bin/* lib64/clang/$VARIANT_TAG/bin
for f in lib64/clang/$VARIANT_TAG/bin/*; do
case "$f" in
*-$VERSION)
# Already versioned, leave it alone
continue
;;
esac
ln -s ../$f bin/${f##*/}-dpcpp
done

# libclang-cpp auto-relocates, so create a symlink so it finds its files
ln -s ../.. lib64/clang/$VARIANT_TAG/lib64

#/usr
popd
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib64/clang/21/include/cuda_wrappers/algorithm
/usr/lib64/clang/21/include/cuda_wrappers/bits/basic_string.tcc
/usr/lib64/clang/21/include/cuda_wrappers/cmath
/usr/lib64/clang/21/include/cuda_wrappers/complex
/usr/lib64/clang/21/include/cuda_wrappers/new
/usr/lib64/clang/21/include/module.modulemap
/usr/lib64/clang/21/include/openmp_wrappers/cmath
/usr/lib64/clang/21/include/openmp_wrappers/complex
/usr/lib64/clang/21/include/openmp_wrappers/new
/usr/lib64/clang/dpcpp/bin/amdgpu-arch
/usr/lib64/clang/dpcpp/bin/analyze-build
/usr/lib64/clang/dpcpp/bin/append-file
/usr/lib64/clang/dpcpp/bin/bugpoint
/usr/lib64/clang/dpcpp/bin/c-index-test
/usr/lib64/clang/dpcpp/bin/clang
/usr/lib64/clang/dpcpp/bin/clang++
/usr/lib64/clang/dpcpp/bin/clang-21
/usr/lib64/clang/dpcpp/bin/clang-check
/usr/lib64/clang/dpcpp/bin/clang-cl
/usr/lib64/clang/dpcpp/bin/clang-cpp
/usr/lib64/clang/dpcpp/bin/clang-extdef-mapping
/usr/lib64/clang/dpcpp/bin/clang-format
/usr/lib64/clang/dpcpp/bin/clang-installapi
/usr/lib64/clang/dpcpp/bin/clang-linker-wrapper
/usr/lib64/clang/dpcpp/bin/clang-nvlink-wrapper
/usr/lib64/clang/dpcpp/bin/clang-offload-bundler
/usr/lib64/clang/dpcpp/bin/clang-offload-deps
/usr/lib64/clang/dpcpp/bin/clang-offload-extract
/usr/lib64/clang/dpcpp/bin/clang-offload-packager
/usr/lib64/clang/dpcpp/bin/clang-offload-wrapper
/usr/lib64/clang/dpcpp/bin/clang-refactor
/usr/lib64/clang/dpcpp/bin/clang-repl
/usr/lib64/clang/dpcpp/bin/clang-scan-deps
/usr/lib64/clang/dpcpp/bin/clang-sycl-linker
/usr/lib64/clang/dpcpp/bin/clang-tblgen
/usr/lib64/clang/dpcpp/bin/cllayerinfo
/usr/lib64/clang/dpcpp/bin/diagtool
/usr/lib64/clang/dpcpp/bin/dsymutil
/usr/lib64/clang/dpcpp/bin/file-table-tform
/usr/lib64/clang/dpcpp/bin/git-clang-format
/usr/lib64/clang/dpcpp/bin/hmaptool
/usr/lib64/clang/dpcpp/bin/intercept-build
/usr/lib64/clang/dpcpp/bin/llc
/usr/lib64/clang/dpcpp/bin/lli
/usr/lib64/clang/dpcpp/bin/llvm-addr2line
/usr/lib64/clang/dpcpp/bin/llvm-ar
/usr/lib64/clang/dpcpp/bin/llvm-as
/usr/lib64/clang/dpcpp/bin/llvm-bcanalyzer
/usr/lib64/clang/dpcpp/bin/llvm-bitcode-strip
/usr/lib64/clang/dpcpp/bin/llvm-c-test
/usr/lib64/clang/dpcpp/bin/llvm-cat
/usr/lib64/clang/dpcpp/bin/llvm-cfi-verify
/usr/lib64/clang/dpcpp/bin/llvm-cgdata
/usr/lib64/clang/dpcpp/bin/llvm-config
/usr/lib64/clang/dpcpp/bin/llvm-cov
/usr/lib64/clang/dpcpp/bin/llvm-ctxprof-util
/usr/lib64/clang/dpcpp/bin/llvm-cvtres
/usr/lib64/clang/dpcpp/bin/llvm-cxxdump
/usr/lib64/clang/dpcpp/bin/llvm-cxxfilt
/usr/lib64/clang/dpcpp/bin/llvm-cxxmap
/usr/lib64/clang/dpcpp/bin/llvm-debuginfo-analyzer
/usr/lib64/clang/dpcpp/bin/llvm-debuginfod
/usr/lib64/clang/dpcpp/bin/llvm-debuginfod-find
/usr/lib64/clang/dpcpp/bin/llvm-diff
/usr/lib64/clang/dpcpp/bin/llvm-dis
/usr/lib64/clang/dpcpp/bin/llvm-dlltool
/usr/lib64/clang/dpcpp/bin/llvm-dwarfdump
/usr/lib64/clang/dpcpp/bin/llvm-dwarfutil
/usr/lib64/clang/dpcpp/bin/llvm-dwp
/usr/lib64/clang/dpcpp/bin/llvm-exegesis
/usr/lib64/clang/dpcpp/bin/llvm-extract
/usr/lib64/clang/dpcpp/bin/llvm-foreach
/usr/lib64/clang/dpcpp/bin/llvm-gsymutil
/usr/lib64/clang/dpcpp/bin/llvm-ifs
/usr/lib64/clang/dpcpp/bin/llvm-install-name-tool
/usr/lib64/clang/dpcpp/bin/llvm-jitlink
/usr/lib64/clang/dpcpp/bin/llvm-lib
/usr/lib64/clang/dpcpp/bin/llvm-libtool-darwin
/usr/lib64/clang/dpcpp/bin/llvm-link
/usr/lib64/clang/dpcpp/bin/llvm-lipo
/usr/lib64/clang/dpcpp/bin/llvm-lto
/usr/lib64/clang/dpcpp/bin/llvm-lto2
/usr/lib64/clang/dpcpp/bin/llvm-mc
/usr/lib64/clang/dpcpp/bin/llvm-mca
/usr/lib64/clang/dpcpp/bin/llvm-ml
/usr/lib64/clang/dpcpp/bin/llvm-ml64
/usr/lib64/clang/dpcpp/bin/llvm-modextract
/usr/lib64/clang/dpcpp/bin/llvm-mt
/usr/lib64/clang/dpcpp/bin/llvm-nm
/usr/lib64/clang/dpcpp/bin/llvm-objcopy
/usr/lib64/clang/dpcpp/bin/llvm-objdump
/usr/lib64/clang/dpcpp/bin/llvm-opt-report
/usr/lib64/clang/dpcpp/bin/llvm-otool
/usr/lib64/clang/dpcpp/bin/llvm-pdbutil
/usr/lib64/clang/dpcpp/bin/llvm-profdata
/usr/lib64/clang/dpcpp/bin/llvm-profgen
/usr/lib64/clang/dpcpp/bin/llvm-ranlib
/usr/lib64/clang/dpcpp/bin/llvm-rc
/usr/lib64/clang/dpcpp/bin/llvm-readelf
/usr/lib64/clang/dpcpp/bin/llvm-readobj
/usr/lib64/clang/dpcpp/bin/llvm-readtapi
/usr/lib64/clang/dpcpp/bin/llvm-reduce
/usr/lib64/clang/dpcpp/bin/llvm-remarkutil
/usr/lib64/clang/dpcpp/bin/llvm-rtdyld
/usr/lib64/clang/dpcpp/bin/llvm-sim
/usr/lib64/clang/dpcpp/bin/llvm-size
/usr/lib64/clang/dpcpp/bin/llvm-spirv
/usr/lib64/clang/dpcpp/bin/llvm-split
/usr/lib64/clang/dpcpp/bin/llvm-stress
/usr/lib64/clang/dpcpp/bin/llvm-strings
/usr/lib64/clang/dpcpp/bin/llvm-strip
/usr/lib64/clang/dpcpp/bin/llvm-symbolizer
/usr/lib64/clang/dpcpp/bin/llvm-tblgen
/usr/lib64/clang/dpcpp/bin/llvm-tli-checker
/usr/lib64/clang/dpcpp/bin/llvm-undname
/usr/lib64/clang/dpcpp/bin/llvm-windres
/usr/lib64/clang/dpcpp/bin/llvm-xray
/usr/lib64/clang/dpcpp/bin/nvptx-arch
/usr/lib64/clang/dpcpp/bin/offload-arch
/usr/lib64/clang/dpcpp/bin/opencl-aot
/usr/lib64/clang/dpcpp/bin/opt
/usr/lib64/clang/dpcpp/bin/reduce-chunk-list
/usr/lib64/clang/dpcpp/bin/sancov
/usr/lib64/clang/dpcpp/bin/sanstats
/usr/lib64/clang/dpcpp/bin/scan-build
/usr/lib64/clang/dpcpp/bin/scan-build-py
/usr/lib64/clang/dpcpp/bin/scan-view
/usr/lib64/clang/dpcpp/bin/spirv-to-ir-wrapper
/usr/lib64/clang/dpcpp/bin/sycl-ls
/usr/lib64/clang/dpcpp/bin/sycl-module-split
/usr/lib64/clang/dpcpp/bin/sycl-post-link
/usr/lib64/clang/dpcpp/bin/syclbin-dump
/usr/lib64/clang/dpcpp/bin/verify-uselistorder
/usr/lib64/clang/dpcpp/lib64
/usr/lib64/libsycl-asan-cpu.bc
/usr/lib64/libsycl-asan-cpu.new.o
/usr/lib64/libsycl-asan-cpu.o
/usr/lib64/libsycl-asan-dg2.bc
/usr/lib64/libsycl-asan-dg2.new.o
/usr/lib64/libsycl-asan-dg2.o
/usr/lib64/libsycl-asan-pvc.bc
/usr/lib64/libsycl-asan-pvc.new.o
/usr/lib64/libsycl-asan-pvc.o
/usr/lib64/libsycl-asan.bc
/usr/lib64/libsycl-asan.new.o
/usr/lib64/libsycl-asan.o
/usr/lib64/libsycl-bfloat16.bc
/usr/lib64/libsycl-bfloat16.new.o
/usr/lib64/libsycl-bfloat16.o
/usr/lib64/libsycl-bfloat16.spv
/usr/lib64/libsycl-cmath-fp64.bc
/usr/lib64/libsycl-cmath-fp64.new.o
/usr/lib64/libsycl-cmath-fp64.o
/usr/lib64/libsycl-cmath-fp64.spv
/usr/lib64/libsycl-cmath.bc
/usr/lib64/libsycl-cmath.new.o
/usr/lib64/libsycl-cmath.o
/usr/lib64/libsycl-cmath.spv
/usr/lib64/libsycl-complex-fp64.bc
/usr/lib64/libsycl-complex-fp64.new.o
/usr/lib64/libsycl-complex-fp64.o
/usr/lib64/libsycl-complex-fp64.spv
/usr/lib64/libsycl-complex.bc
/usr/lib64/libsycl-complex.new.o
/usr/lib64/libsycl-complex.o
/usr/lib64/libsycl-complex.spv
/usr/lib64/libsycl-crt.bc
/usr/lib64/libsycl-crt.new.o
/usr/lib64/libsycl-crt.o
/usr/lib64/libsycl-crt.spv
/usr/lib64/libsycl-fallback-bfloat16.bc
/usr/lib64/libsycl-fallback-bfloat16.new.o
/usr/lib64/libsycl-fallback-bfloat16.o
/usr/lib64/libsycl-fallback-cassert.bc
/usr/lib64/libsycl-fallback-cassert.new.o
/usr/lib64/libsycl-fallback-cassert.o
/usr/lib64/libsycl-fallback-cassert.spv
/usr/lib64/libsycl-fallback-cmath-fp64.bc
/usr/lib64/libsycl-fallback-cmath-fp64.new.o
/usr/lib64/libsycl-fallback-cmath-fp64.o
/usr/lib64/libsycl-fallback-cmath-fp64.spv
/usr/lib64/libsycl-fallback-cmath.bc
/usr/lib64/libsycl-fallback-cmath.new.o
/usr/lib64/libsycl-fallback-cmath.o
/usr/lib64/libsycl-fallback-cmath.spv
/usr/lib64/libsycl-fallback-complex-fp64.bc
/usr/lib64/libsycl-fallback-complex-fp64.new.o
/usr/lib64/libsycl-fallback-complex-fp64.o
/usr/lib64/libsycl-fallback-complex-fp64.spv
/usr/lib64/libsycl-fallback-complex.bc
/usr/lib64/libsycl-fallback-complex.new.o
/usr/lib64/libsycl-fallback-complex.o
/usr/lib64/libsycl-fallback-complex.spv
/usr/lib64/libsycl-fallback-cstring.bc
/usr/lib64/libsycl-fallback-cstring.new.o
/usr/lib64/libsycl-fallback-cstring.o
/usr/lib64/libsycl-fallback-cstring.spv
/usr/lib64/libsycl-fallback-imf-bf16.bc
/usr/lib64/libsycl-fallback-imf-bf16.new.o
/usr/lib64/libsycl-fallback-imf-bf16.o
/usr/lib64/libsycl-fallback-imf-bf16.spv
/usr/lib64/libsycl-fallback-imf-fp64.bc
/usr/lib64/libsycl-fallback-imf-fp64.new.o
/usr/lib64/libsycl-fallback-imf-fp64.o
/usr/lib64/libsycl-fallback-imf-fp64.spv
/usr/lib64/libsycl-fallback-imf.bc
/usr/lib64/libsycl-fallback-imf.new.o
/usr/lib64/libsycl-fallback-imf.o
/usr/lib64/libsycl-fallback-imf.spv
/usr/lib64/libsycl-imf-bf16.bc
/usr/lib64/libsycl-imf-bf16.new.o
/usr/lib64/libsycl-imf-bf16.o
/usr/lib64/libsycl-imf-bf16.spv
/usr/lib64/libsycl-imf-fp64.bc
/usr/lib64/libsycl-imf-fp64.new.o
/usr/lib64/libsycl-imf-fp64.o
/usr/lib64/libsycl-imf-fp64.spv
/usr/lib64/libsycl-imf.bc
/usr/lib64/libsycl-imf.new.o
/usr/lib64/libsycl-imf.o
/usr/lib64/libsycl-imf.spv
/usr/lib64/libsycl-itt-compiler-wrappers.bc
/usr/lib64/libsycl-itt-compiler-wrappers.new.o
/usr/lib64/libsycl-itt-compiler-wrappers.o
/usr/lib64/libsycl-itt-compiler-wrappers.spv
/usr/lib64/libsycl-itt-stubs.bc
/usr/lib64/libsycl-itt-stubs.new.o
/usr/lib64/libsycl-itt-stubs.o
/usr/lib64/libsycl-itt-stubs.spv
/usr/lib64/libsycl-itt-user-wrappers.bc
/usr/lib64/libsycl-itt-user-wrappers.new.o
/usr/lib64/libsycl-itt-user-wrappers.o
/usr/lib64/libsycl-itt-user-wrappers.spv
/usr/lib64/libsycl-msan-cpu.bc
/usr/lib64/libsycl-msan-cpu.new.o
/usr/lib64/libsycl-msan-cpu.o
/usr/lib64/libsycl-msan-pvc.bc
/usr/lib64/libsycl-msan-pvc.new.o
/usr/lib64/libsycl-msan-pvc.o
/usr/lib64/libsycl-msan.bc
/usr/lib64/libsycl-msan.new.o
/usr/lib64/libsycl-msan.o
/usr/lib64/libsycl-native-bfloat16.bc
/usr/lib64/libsycl-native-bfloat16.new.o
/usr/lib64/libsycl-native-bfloat16.o
/usr/lib64/libsycl-tsan-cpu.bc
/usr/lib64/libsycl-tsan-cpu.new.o
/usr/lib64/libsycl-tsan-cpu.o
/usr/lib64/libsycl-tsan-pvc.bc
/usr/lib64/libsycl-tsan-pvc.new.o
/usr/lib64/libsycl-tsan-pvc.o
/usr/lib64/libsycl-tsan.bc
/usr/lib64/libsycl-tsan.new.o
/usr/lib64/libsycl-tsan.o

%files bin
%defattr(-,root,root,-)
/usr/bin/amdgpu-arch-dpcpp
/usr/bin/analyze-build-dpcpp
/usr/bin/append-file-dpcpp
/usr/bin/bugpoint-dpcpp
/usr/bin/c-index-test-dpcpp
/usr/bin/clang++-dpcpp
/usr/bin/clang-21-dpcpp
/usr/bin/clang-check-dpcpp
/usr/bin/clang-cl-dpcpp
/usr/bin/clang-cpp-dpcpp
/usr/bin/clang-dpcpp
/usr/bin/clang-extdef-mapping-dpcpp
/usr/bin/clang-format-dpcpp
/usr/bin/clang-installapi-dpcpp
/usr/bin/clang-linker-wrapper-dpcpp
/usr/bin/clang-nvlink-wrapper-dpcpp
/usr/bin/clang-offload-bundler-dpcpp
/usr/bin/clang-offload-deps-dpcpp
/usr/bin/clang-offload-extract-dpcpp
/usr/bin/clang-offload-packager-dpcpp
/usr/bin/clang-offload-wrapper-dpcpp
/usr/bin/clang-refactor-dpcpp
/usr/bin/clang-repl-dpcpp
/usr/bin/clang-scan-deps-dpcpp
/usr/bin/clang-sycl-linker-dpcpp
/usr/bin/clang-tblgen-dpcpp
/usr/bin/cllayerinfo-dpcpp
/usr/bin/diagtool-dpcpp
/usr/bin/dsymutil-dpcpp
/usr/bin/file-table-tform-dpcpp
/usr/bin/git-clang-format-dpcpp
/usr/bin/hmaptool-dpcpp
/usr/bin/intercept-build-dpcpp
/usr/bin/llc-dpcpp
/usr/bin/lli-dpcpp
/usr/bin/llvm-addr2line-dpcpp
/usr/bin/llvm-ar-dpcpp
/usr/bin/llvm-as-dpcpp
/usr/bin/llvm-bcanalyzer-dpcpp
/usr/bin/llvm-bitcode-strip-dpcpp
/usr/bin/llvm-c-test-dpcpp
/usr/bin/llvm-cat-dpcpp
/usr/bin/llvm-cfi-verify-dpcpp
/usr/bin/llvm-cgdata-dpcpp
/usr/bin/llvm-config-dpcpp
/usr/bin/llvm-cov-dpcpp
/usr/bin/llvm-ctxprof-util-dpcpp
/usr/bin/llvm-cvtres-dpcpp
/usr/bin/llvm-cxxdump-dpcpp
/usr/bin/llvm-cxxfilt-dpcpp
/usr/bin/llvm-cxxmap-dpcpp
/usr/bin/llvm-debuginfo-analyzer-dpcpp
/usr/bin/llvm-debuginfod-dpcpp
/usr/bin/llvm-debuginfod-find-dpcpp
/usr/bin/llvm-diff-dpcpp
/usr/bin/llvm-dis-dpcpp
/usr/bin/llvm-dlltool-dpcpp
/usr/bin/llvm-dwarfdump-dpcpp
/usr/bin/llvm-dwarfutil-dpcpp
/usr/bin/llvm-dwp-dpcpp
/usr/bin/llvm-exegesis-dpcpp
/usr/bin/llvm-extract-dpcpp
/usr/bin/llvm-foreach-dpcpp
/usr/bin/llvm-gsymutil-dpcpp
/usr/bin/llvm-ifs-dpcpp
/usr/bin/llvm-install-name-tool-dpcpp
/usr/bin/llvm-jitlink-dpcpp
/usr/bin/llvm-lib-dpcpp
/usr/bin/llvm-libtool-darwin-dpcpp
/usr/bin/llvm-link-dpcpp
/usr/bin/llvm-lipo-dpcpp
/usr/bin/llvm-lto-dpcpp
/usr/bin/llvm-lto2-dpcpp
/usr/bin/llvm-mc-dpcpp
/usr/bin/llvm-mca-dpcpp
/usr/bin/llvm-ml-dpcpp
/usr/bin/llvm-ml64-dpcpp
/usr/bin/llvm-modextract-dpcpp
/usr/bin/llvm-mt-dpcpp
/usr/bin/llvm-nm-dpcpp
/usr/bin/llvm-objcopy-dpcpp
/usr/bin/llvm-objdump-dpcpp
/usr/bin/llvm-opt-report-dpcpp
/usr/bin/llvm-otool-dpcpp
/usr/bin/llvm-pdbutil-dpcpp
/usr/bin/llvm-profdata-dpcpp
/usr/bin/llvm-profgen-dpcpp
/usr/bin/llvm-ranlib-dpcpp
/usr/bin/llvm-rc-dpcpp
/usr/bin/llvm-readelf-dpcpp
/usr/bin/llvm-readobj-dpcpp
/usr/bin/llvm-readtapi-dpcpp
/usr/bin/llvm-reduce-dpcpp
/usr/bin/llvm-remarkutil-dpcpp
/usr/bin/llvm-rtdyld-dpcpp
/usr/bin/llvm-sim-dpcpp
/usr/bin/llvm-size-dpcpp
/usr/bin/llvm-spirv-dpcpp
/usr/bin/llvm-split-dpcpp
/usr/bin/llvm-stress-dpcpp
/usr/bin/llvm-strings-dpcpp
/usr/bin/llvm-strip-dpcpp
/usr/bin/llvm-symbolizer-dpcpp
/usr/bin/llvm-tblgen-dpcpp
/usr/bin/llvm-tli-checker-dpcpp
/usr/bin/llvm-undname-dpcpp
/usr/bin/llvm-windres-dpcpp
/usr/bin/llvm-xray-dpcpp
/usr/bin/nvptx-arch-dpcpp
/usr/bin/offload-arch-dpcpp
/usr/bin/opencl-aot-dpcpp
/usr/bin/opt-dpcpp
/usr/bin/reduce-chunk-list-dpcpp
/usr/bin/sancov-dpcpp
/usr/bin/sanstats-dpcpp
/usr/bin/scan-build-dpcpp
/usr/bin/scan-build-py-dpcpp
/usr/bin/scan-view-dpcpp
/usr/bin/spirv-to-ir-wrapper-dpcpp
/usr/bin/sycl-ls-dpcpp
/usr/bin/sycl-module-split-dpcpp
/usr/bin/sycl-post-link-dpcpp
/usr/bin/syclbin-dump-dpcpp
/usr/bin/verify-uselistorder-dpcpp

%files data
%defattr(-,root,root,-)
/usr/share/cmake/*

%files dev
%defattr(-,root,root,-)
/usr/include/CL/sycl.hpp
/usr/include/llvm/Frontend/Offloading/SYCLOffloadWrapper.h
/usr/include/llvm/Object/SYCLBIN.h
/usr/include/llvm/SYCLLowerIR/CleanupSYCLMetadata.h
/usr/include/llvm/SYCLLowerIR/CompileTimePropertiesPass.h
/usr/include/llvm/SYCLLowerIR/ConvertToMuxBuiltinsSYCLNativeCPU.h
/usr/include/llvm/SYCLLowerIR/DeviceConfigFile.inc
/usr/include/llvm/SYCLLowerIR/DeviceConfigFile.td
/usr/include/llvm/SYCLLowerIR/DeviceGlobals.h
/usr/include/llvm/SYCLLowerIR/ESIMD/ESIMDUtils.h
/usr/include/llvm/SYCLLowerIR/ESIMD/ESIMDVerifier.h
/usr/include/llvm/SYCLLowerIR/ESIMD/LowerESIMD.h
/usr/include/llvm/SYCLLowerIR/FAtomicsNativeCPU.h
/usr/include/llvm/SYCLLowerIR/GlobalOffset.h
/usr/include/llvm/SYCLLowerIR/HostPipes.h
/usr/include/llvm/SYCLLowerIR/LocalAccessorToSharedMemory.h
/usr/include/llvm/SYCLLowerIR/LowerInvokeSimd.h
/usr/include/llvm/SYCLLowerIR/LowerWGLocalMemory.h
/usr/include/llvm/SYCLLowerIR/LowerWGScope.h
/usr/include/llvm/SYCLLowerIR/MutatePrintfAddrspace.h
/usr/include/llvm/SYCLLowerIR/PrepareSYCLNativeCPU.h
/usr/include/llvm/SYCLLowerIR/RecordSYCLAspectNames.h
/usr/include/llvm/SYCLLowerIR/RenameKernelSYCLNativeCPU.h
/usr/include/llvm/SYCLLowerIR/SYCLAddOptLevelAttribute.h
/usr/include/llvm/SYCLLowerIR/SYCLConditionalCallOnDevice.h
/usr/include/llvm/SYCLLowerIR/SYCLCreateNVVMAnnotations.h
/usr/include/llvm/SYCLLowerIR/SYCLDeviceLibReqMask.h
/usr/include/llvm/SYCLLowerIR/SYCLDeviceRequirements.h
/usr/include/llvm/SYCLLowerIR/SYCLJointMatrixTransform.h
/usr/include/llvm/SYCLLowerIR/SYCLKernelParamOptInfo.h
/usr/include/llvm/SYCLLowerIR/SYCLOptimizeBackToBackBarrier.h
/usr/include/llvm/SYCLLowerIR/SYCLPropagateAspectsUsage.h
/usr/include/llvm/SYCLLowerIR/SYCLPropagateJointMatrixUsage.h
/usr/include/llvm/SYCLLowerIR/SYCLUtils.h
/usr/include/llvm/SYCLLowerIR/SYCLVirtualFunctionsAnalysis.h
/usr/include/llvm/SYCLLowerIR/SanitizerKernelMetadata.h
/usr/include/llvm/SYCLLowerIR/SpecConstants.h
/usr/include/llvm/SYCLLowerIR/Support.h
/usr/include/llvm/SYCLLowerIR/TargetHelpers.h
/usr/include/llvm/SYCLLowerIR/UtilsSYCLNativeCPU.h
/usr/include/llvm/SYCLPostLink/ComputeModuleRuntimeInfo.h
/usr/include/llvm/SYCLPostLink/ESIMDPostSplitProcessing.h
/usr/include/llvm/SYCLPostLink/ModuleSplitter.h
/usr/include/sycl/__spirv/spirv_ops.hpp
/usr/include/sycl/__spirv/spirv_types.hpp
/usr/include/sycl/__spirv/spirv_vars.hpp
/usr/include/sycl/access/access.hpp
/usr/include/sycl/accessor.hpp
/usr/include/sycl/accessor_image.hpp
/usr/include/sycl/aliases.hpp
/usr/include/sycl/aspects.hpp
/usr/include/sycl/async_handler.hpp
/usr/include/sycl/atomic.hpp
/usr/include/sycl/atomic_fence.hpp
/usr/include/sycl/atomic_ref.hpp
/usr/include/sycl/backend.hpp
/usr/include/sycl/backend/cuda.hpp
/usr/include/sycl/backend/level_zero.hpp
/usr/include/sycl/backend/opencl.hpp
/usr/include/sycl/backend_types.hpp
/usr/include/sycl/bit_cast.hpp
/usr/include/sycl/buffer.hpp
/usr/include/sycl/builtins.hpp
/usr/include/sycl/builtins_esimd.hpp
/usr/include/sycl/context.hpp
/usr/include/sycl/define_vendors.hpp
/usr/include/sycl/detail/accessor_iterator.hpp
/usr/include/sycl/detail/aligned_allocator.hpp
/usr/include/sycl/detail/array.hpp
/usr/include/sycl/detail/assert_happened.hpp
/usr/include/sycl/detail/backend_traits.hpp
/usr/include/sycl/detail/backend_traits_cuda.hpp
/usr/include/sycl/detail/backend_traits_hip.hpp
/usr/include/sycl/detail/backend_traits_level_zero.hpp
/usr/include/sycl/detail/backend_traits_opencl.hpp
/usr/include/sycl/detail/builtins/builtins.hpp
/usr/include/sycl/detail/builtins/common_functions.inc
/usr/include/sycl/detail/builtins/geometric_functions.inc
/usr/include/sycl/detail/builtins/half_precision_math_functions.inc
/usr/include/sycl/detail/builtins/helper_macros.hpp
/usr/include/sycl/detail/builtins/integer_functions.inc
/usr/include/sycl/detail/builtins/math_functions.inc
/usr/include/sycl/detail/builtins/native_math_functions.inc
/usr/include/sycl/detail/builtins/relational_functions.inc
/usr/include/sycl/detail/cg_types.hpp
/usr/include/sycl/detail/cl.h
/usr/include/sycl/detail/common.hpp
/usr/include/sycl/detail/core.hpp
/usr/include/sycl/detail/defines.hpp
/usr/include/sycl/detail/defines_elementary.hpp
/usr/include/sycl/detail/device_filter.hpp
/usr/include/sycl/detail/device_global_map.hpp
/usr/include/sycl/detail/export.hpp
/usr/include/sycl/detail/generic_type_traits.hpp
/usr/include/sycl/detail/group_sort_impl.hpp
/usr/include/sycl/detail/handler_proxy.hpp
/usr/include/sycl/detail/helpers.hpp
/usr/include/sycl/detail/host_pipe_map.hpp
/usr/include/sycl/detail/host_profiling_info.hpp
/usr/include/sycl/detail/id_queries_fit_in_int.hpp
/usr/include/sycl/detail/image_accessor_util.hpp
/usr/include/sycl/detail/image_ocl_types.hpp
/usr/include/sycl/detail/impl_utils.hpp
/usr/include/sycl/detail/info_desc_helpers.hpp
/usr/include/sycl/detail/iostream_proxy.hpp
/usr/include/sycl/detail/is_device_copyable.hpp
/usr/include/sycl/detail/item_base.hpp
/usr/include/sycl/detail/kernel_desc.hpp
/usr/include/sycl/detail/kernel_name_based_cache.hpp
/usr/include/sycl/detail/kernel_name_str_t.hpp
/usr/include/sycl/detail/kernel_properties.hpp
/usr/include/sycl/detail/key_value_iterator.hpp
/usr/include/sycl/detail/locked.hpp
/usr/include/sycl/detail/memcpy.hpp
/usr/include/sycl/detail/named_swizzles_mixin.hpp
/usr/include/sycl/detail/optional.hpp
/usr/include/sycl/detail/os_util.hpp
/usr/include/sycl/detail/owner_less_base.hpp
/usr/include/sycl/detail/property_helper.hpp
/usr/include/sycl/detail/property_list_base.hpp
/usr/include/sycl/detail/reduction_forward.hpp
/usr/include/sycl/detail/spec_const_integration.hpp
/usr/include/sycl/detail/spinlock.hpp
/usr/include/sycl/detail/spirv.hpp
/usr/include/sycl/detail/stl_type_traits.hpp
/usr/include/sycl/detail/string.hpp
/usr/include/sycl/detail/string_view.hpp
/usr/include/sycl/detail/sycl_local_mem_builtins.hpp
/usr/include/sycl/detail/sycl_mem_obj_allocator.hpp
/usr/include/sycl/detail/tuple.hpp
/usr/include/sycl/detail/type_traits.hpp
/usr/include/sycl/detail/type_traits/vec_marray_traits.hpp
/usr/include/sycl/detail/ur.hpp
/usr/include/sycl/detail/usm_impl.hpp
/usr/include/sycl/detail/util.hpp
/usr/include/sycl/detail/vector_arith.hpp
/usr/include/sycl/detail/vector_convert.hpp
/usr/include/sycl/device.hpp
/usr/include/sycl/device_aspect_macros.hpp
/usr/include/sycl/device_aspect_traits.hpp
/usr/include/sycl/device_event.hpp
/usr/include/sycl/device_selector.hpp
/usr/include/sycl/event.hpp
/usr/include/sycl/exception.hpp
/usr/include/sycl/exception_list.hpp
/usr/include/sycl/ext/codeplay/experimental/fusion_wrapper.hpp
/usr/include/sycl/ext/intel/esimd.hpp
/usr/include/sycl/ext/intel/esimd/alt_ui.hpp
/usr/include/sycl/ext/intel/esimd/common.hpp
/usr/include/sycl/ext/intel/esimd/detail/bfloat16_type_traits.hpp
/usr/include/sycl/ext/intel/esimd/detail/defines_elementary.hpp
/usr/include/sycl/ext/intel/esimd/detail/elem_type_traits.hpp
/usr/include/sycl/ext/intel/esimd/detail/half_type_traits.hpp
/usr/include/sycl/ext/intel/esimd/detail/intrin.hpp
/usr/include/sycl/ext/intel/esimd/detail/math_intrin.hpp
/usr/include/sycl/ext/intel/esimd/detail/memory_intrin.hpp
/usr/include/sycl/ext/intel/esimd/detail/operators.hpp
/usr/include/sycl/ext/intel/esimd/detail/region.hpp
/usr/include/sycl/ext/intel/esimd/detail/simd_mask_impl.hpp
/usr/include/sycl/ext/intel/esimd/detail/simd_obj_impl.hpp
/usr/include/sycl/ext/intel/esimd/detail/simd_view_impl.hpp
/usr/include/sycl/ext/intel/esimd/detail/sycl_util.hpp
/usr/include/sycl/ext/intel/esimd/detail/tfloat32_type_traits.hpp
/usr/include/sycl/ext/intel/esimd/detail/type_format.hpp
/usr/include/sycl/ext/intel/esimd/detail/types.hpp
/usr/include/sycl/ext/intel/esimd/detail/types_elementary.hpp
/usr/include/sycl/ext/intel/esimd/detail/util.hpp
/usr/include/sycl/ext/intel/esimd/math.hpp
/usr/include/sycl/ext/intel/esimd/memory.hpp
/usr/include/sycl/ext/intel/esimd/memory_properties.hpp
/usr/include/sycl/ext/intel/esimd/native/common.hpp
/usr/include/sycl/ext/intel/esimd/simd.hpp
/usr/include/sycl/ext/intel/esimd/simd_view.hpp
/usr/include/sycl/ext/intel/esimd/xmx/common.hpp
/usr/include/sycl/ext/intel/esimd/xmx/dpas.hpp
/usr/include/sycl/ext/intel/experimental/cache_control_properties.hpp
/usr/include/sycl/ext/intel/experimental/detail/misc_intrin.hpp
/usr/include/sycl/ext/intel/experimental/esimd/common.hpp
/usr/include/sycl/ext/intel/experimental/esimd/detail/math_intrin.hpp
/usr/include/sycl/ext/intel/experimental/esimd/detail/memory_intrin.hpp
/usr/include/sycl/ext/intel/experimental/esimd/detail/util.hpp
/usr/include/sycl/ext/intel/experimental/esimd/math.hpp
/usr/include/sycl/ext/intel/experimental/esimd/memory.hpp
/usr/include/sycl/ext/intel/experimental/esimd/tfloat32.hpp
/usr/include/sycl/ext/intel/experimental/fp_control_kernel_properties.hpp
/usr/include/sycl/ext/intel/experimental/fpga_annotated_properties.hpp
/usr/include/sycl/ext/intel/experimental/fpga_kernel_properties.hpp
/usr/include/sycl/ext/intel/experimental/fpga_lsu.hpp
/usr/include/sycl/ext/intel/experimental/fpga_mem/fpga_datapath.hpp
/usr/include/sycl/ext/intel/experimental/fpga_mem/fpga_mem.hpp
/usr/include/sycl/ext/intel/experimental/fpga_mem/properties.hpp
/usr/include/sycl/ext/intel/experimental/fpga_utils.hpp
/usr/include/sycl/ext/intel/experimental/grf_size_properties.hpp
/usr/include/sycl/ext/intel/experimental/kernel_execution_properties.hpp
/usr/include/sycl/ext/intel/experimental/pipe_properties.hpp
/usr/include/sycl/ext/intel/experimental/pipes.hpp
/usr/include/sycl/ext/intel/experimental/task_sequence.hpp
/usr/include/sycl/ext/intel/experimental/task_sequence_properties.hpp
/usr/include/sycl/ext/intel/experimental/usm_properties.hpp
/usr/include/sycl/ext/intel/fpga_device_selector.hpp
/usr/include/sycl/ext/intel/fpga_dsp_control.hpp
/usr/include/sycl/ext/intel/fpga_extensions.hpp
/usr/include/sycl/ext/intel/fpga_loop_fuse.hpp
/usr/include/sycl/ext/intel/fpga_lsu.hpp
/usr/include/sycl/ext/intel/fpga_reg.hpp
/usr/include/sycl/ext/intel/fpga_utils.hpp
/usr/include/sycl/ext/intel/math.hpp
/usr/include/sycl/ext/intel/math/imf_fp_conversions.hpp
/usr/include/sycl/ext/intel/math/imf_half_trivial.hpp
/usr/include/sycl/ext/intel/math/imf_integer_utils.hpp
/usr/include/sycl/ext/intel/math/imf_rounding_math.hpp
/usr/include/sycl/ext/intel/math/imf_simd.hpp
/usr/include/sycl/ext/intel/pipes.hpp
/usr/include/sycl/ext/intel/usm_pointers.hpp
/usr/include/sycl/ext/oneapi/accessor_property_list.hpp
/usr/include/sycl/ext/oneapi/backend/hip.hpp
/usr/include/sycl/ext/oneapi/backend/level_zero.hpp
/usr/include/sycl/ext/oneapi/backend/level_zero_ownership.hpp
/usr/include/sycl/ext/oneapi/bf16_storage_builtins.hpp
/usr/include/sycl/ext/oneapi/bfloat16.hpp
/usr/include/sycl/ext/oneapi/bindless_images.hpp
/usr/include/sycl/ext/oneapi/bindless_images_descriptor.hpp
/usr/include/sycl/ext/oneapi/bindless_images_interop.hpp
/usr/include/sycl/ext/oneapi/bindless_images_mem_handle.hpp
/usr/include/sycl/ext/oneapi/bindless_images_memory.hpp
/usr/include/sycl/ext/oneapi/bindless_images_sampler.hpp
/usr/include/sycl/ext/oneapi/device_global/device_global.hpp
/usr/include/sycl/ext/oneapi/device_global/properties.hpp
/usr/include/sycl/ext/oneapi/dot_product.hpp
/usr/include/sycl/ext/oneapi/experimental/address_cast.hpp
/usr/include/sycl/ext/oneapi/experimental/alloca.hpp
/usr/include/sycl/ext/oneapi/experimental/annotated_arg/annotated_arg.hpp
/usr/include/sycl/ext/oneapi/experimental/annotated_ptr/annotated_ptr.hpp
/usr/include/sycl/ext/oneapi/experimental/annotated_ptr/annotated_ptr_properties.hpp
/usr/include/sycl/ext/oneapi/experimental/annotated_usm/alloc_base.hpp
/usr/include/sycl/ext/oneapi/experimental/annotated_usm/alloc_device.hpp
/usr/include/sycl/ext/oneapi/experimental/annotated_usm/alloc_host.hpp
/usr/include/sycl/ext/oneapi/experimental/annotated_usm/alloc_shared.hpp
/usr/include/sycl/ext/oneapi/experimental/annotated_usm/alloc_util.hpp
/usr/include/sycl/ext/oneapi/experimental/annotated_usm/dealloc.hpp
/usr/include/sycl/ext/oneapi/experimental/async_alloc/async_alloc.hpp
/usr/include/sycl/ext/oneapi/experimental/async_alloc/memory_pool.hpp
/usr/include/sycl/ext/oneapi/experimental/async_alloc/memory_pool_properties.hpp
/usr/include/sycl/ext/oneapi/experimental/auto_local_range.hpp
/usr/include/sycl/ext/oneapi/experimental/backend/backend_traits_cuda.hpp
/usr/include/sycl/ext/oneapi/experimental/backend/cuda.hpp
/usr/include/sycl/ext/oneapi/experimental/ballot_group.hpp
/usr/include/sycl/ext/oneapi/experimental/bfloat16_math.hpp
/usr/include/sycl/ext/oneapi/experimental/builtins.hpp
/usr/include/sycl/ext/oneapi/experimental/cluster_group_prop.hpp
/usr/include/sycl/ext/oneapi/experimental/common_annotated_properties/properties.hpp
/usr/include/sycl/ext/oneapi/experimental/complex/complex.hpp
/usr/include/sycl/ext/oneapi/experimental/complex/detail/common.hpp
/usr/include/sycl/ext/oneapi/experimental/complex/detail/complex.hpp
/usr/include/sycl/ext/oneapi/experimental/complex/detail/complex_math.hpp
/usr/include/sycl/ext/oneapi/experimental/composite_device.hpp
/usr/include/sycl/ext/oneapi/experimental/cuda/barrier.hpp
/usr/include/sycl/ext/oneapi/experimental/cuda/builtins.hpp
/usr/include/sycl/ext/oneapi/experimental/cuda/masked_shuffles.hpp
/usr/include/sycl/ext/oneapi/experimental/cuda/non_uniform_algorithms.hpp
/usr/include/sycl/ext/oneapi/experimental/current_device.hpp
/usr/include/sycl/ext/oneapi/experimental/detail/invoke_simd_types.hpp
/usr/include/sycl/ext/oneapi/experimental/detail/properties/graph_properties.def
/usr/include/sycl/ext/oneapi/experimental/detail/properties/graph_properties.hpp
/usr/include/sycl/ext/oneapi/experimental/detail/properties/node_properties.def
/usr/include/sycl/ext/oneapi/experimental/device_architecture.def
/usr/include/sycl/ext/oneapi/experimental/device_architecture.hpp
/usr/include/sycl/ext/oneapi/experimental/enqueue_functions.hpp
/usr/include/sycl/ext/oneapi/experimental/event_mode_property.hpp
/usr/include/sycl/ext/oneapi/experimental/fixed_size_group.hpp
/usr/include/sycl/ext/oneapi/experimental/forward_progress.hpp
/usr/include/sycl/ext/oneapi/experimental/free_function_traits.hpp
/usr/include/sycl/ext/oneapi/experimental/graph.hpp
/usr/include/sycl/ext/oneapi/experimental/group_helpers_sorters.hpp
/usr/include/sycl/ext/oneapi/experimental/group_load_store.hpp
/usr/include/sycl/ext/oneapi/experimental/group_sort.hpp
/usr/include/sycl/ext/oneapi/experimental/invoke_simd.hpp
/usr/include/sycl/ext/oneapi/experimental/non_uniform_groups.hpp
/usr/include/sycl/ext/oneapi/experimental/opportunistic_group.hpp
/usr/include/sycl/ext/oneapi/experimental/prefetch.hpp
/usr/include/sycl/ext/oneapi/experimental/profiling_tag.hpp
/usr/include/sycl/ext/oneapi/experimental/raw_kernel_arg.hpp
/usr/include/sycl/ext/oneapi/experimental/reduction_properties.hpp
/usr/include/sycl/ext/oneapi/experimental/root_group.hpp
/usr/include/sycl/ext/oneapi/experimental/tangle_group.hpp
/usr/include/sycl/ext/oneapi/experimental/uniform.hpp
/usr/include/sycl/ext/oneapi/experimental/use_root_sync_prop.hpp
/usr/include/sycl/ext/oneapi/experimental/user_defined_reductions.hpp
/usr/include/sycl/ext/oneapi/experimental/virtual_functions.hpp
/usr/include/sycl/ext/oneapi/experimental/work_group_memory.hpp
/usr/include/sycl/ext/oneapi/filter_selector.hpp
/usr/include/sycl/ext/oneapi/free_function_queries.hpp
/usr/include/sycl/ext/oneapi/functional.hpp
/usr/include/sycl/ext/oneapi/get_kernel_info.hpp
/usr/include/sycl/ext/oneapi/group_local_memory.hpp
/usr/include/sycl/ext/oneapi/kernel_properties/properties.hpp
/usr/include/sycl/ext/oneapi/latency_control/properties.hpp
/usr/include/sycl/ext/oneapi/matrix/matrix-hip.hpp
/usr/include/sycl/ext/oneapi/matrix/matrix-intel.hpp
/usr/include/sycl/ext/oneapi/matrix/matrix-tensorcores.hpp
/usr/include/sycl/ext/oneapi/matrix/matrix-unified-utils.hpp
/usr/include/sycl/ext/oneapi/matrix/matrix-unified.hpp
/usr/include/sycl/ext/oneapi/matrix/matrix.hpp
/usr/include/sycl/ext/oneapi/matrix/query-types.hpp
/usr/include/sycl/ext/oneapi/matrix/static-query-use.hpp
/usr/include/sycl/ext/oneapi/matrix/utils.hpp
/usr/include/sycl/ext/oneapi/memcpy2d.hpp
/usr/include/sycl/ext/oneapi/owner_less.hpp
/usr/include/sycl/ext/oneapi/properties/properties.hpp
/usr/include/sycl/ext/oneapi/properties/property.hpp
/usr/include/sycl/ext/oneapi/properties/property_utils.hpp
/usr/include/sycl/ext/oneapi/properties/property_value.hpp
/usr/include/sycl/ext/oneapi/sub_group.hpp
/usr/include/sycl/ext/oneapi/sub_group_mask.hpp
/usr/include/sycl/ext/oneapi/virtual_mem/physical_mem.hpp
/usr/include/sycl/ext/oneapi/virtual_mem/virtual_mem.hpp
/usr/include/sycl/ext/oneapi/weak_object.hpp
/usr/include/sycl/ext/oneapi/weak_object_base.hpp
/usr/include/sycl/ext/oneapi/work_group_scratch_memory.hpp
/usr/include/sycl/ext/oneapi/work_group_static.hpp
/usr/include/sycl/feature_test.hpp
/usr/include/sycl/functional.hpp
/usr/include/sycl/group.hpp
/usr/include/sycl/group_algorithm.hpp
/usr/include/sycl/group_barrier.hpp
/usr/include/sycl/h_item.hpp
/usr/include/sycl/half_type.hpp
/usr/include/sycl/handler.hpp
/usr/include/sycl/id.hpp
/usr/include/sycl/image.hpp
/usr/include/sycl/info/aspects.def
/usr/include/sycl/info/aspects_deprecated.def
/usr/include/sycl/info/context_traits.def
/usr/include/sycl/info/device_traits.def
/usr/include/sycl/info/device_traits_2020_deprecated.def
/usr/include/sycl/info/device_traits_deprecated.def
/usr/include/sycl/info/event_profiling_traits.def
/usr/include/sycl/info/event_traits.def
/usr/include/sycl/info/ext_codeplay_device_traits.def
/usr/include/sycl/info/ext_intel_device_traits.def
/usr/include/sycl/info/ext_intel_kernel_info_traits.def
/usr/include/sycl/info/ext_oneapi_device_traits.def
/usr/include/sycl/info/ext_oneapi_kernel_queue_specific_traits.def
/usr/include/sycl/info/info_desc.hpp
/usr/include/sycl/info/kernel_device_specific_traits.def
/usr/include/sycl/info/kernel_traits.def
/usr/include/sycl/info/platform_traits.def
/usr/include/sycl/info/queue_traits.def
/usr/include/sycl/info/sycl_backend_traits.def
/usr/include/sycl/interop_handle.hpp
/usr/include/sycl/item.hpp
/usr/include/sycl/kernel.hpp
/usr/include/sycl/kernel_bundle.hpp
/usr/include/sycl/kernel_bundle_enums.hpp
/usr/include/sycl/kernel_handler.hpp
/usr/include/sycl/khr/free_function_commands.hpp
/usr/include/sycl/khr/group_interface.hpp
/usr/include/sycl/known_identity.hpp
/usr/include/sycl/marray.hpp
/usr/include/sycl/memory_enums.hpp
/usr/include/sycl/multi_ptr.hpp
/usr/include/sycl/nd_item.hpp
/usr/include/sycl/nd_range.hpp
/usr/include/sycl/pipes.hpp
/usr/include/sycl/platform.hpp
/usr/include/sycl/pointers.hpp
/usr/include/sycl/properties/accessor_properties.hpp
/usr/include/sycl/properties/all_properties.hpp
/usr/include/sycl/properties/buffer_properties.def
/usr/include/sycl/properties/buffer_properties.hpp
/usr/include/sycl/properties/image_properties.def
/usr/include/sycl/properties/image_properties.hpp
/usr/include/sycl/properties/property_traits.hpp
/usr/include/sycl/properties/queue_properties.def
/usr/include/sycl/properties/queue_properties.hpp
/usr/include/sycl/properties/reduction_properties.def
/usr/include/sycl/properties/reduction_properties.hpp
/usr/include/sycl/properties/runtime_accessor_properties.def
/usr/include/sycl/property_list.hpp
/usr/include/sycl/property_list_conversion.hpp
/usr/include/sycl/queue.hpp
/usr/include/sycl/range.hpp
/usr/include/sycl/reduction.hpp
/usr/include/sycl/sampler.hpp
/usr/include/sycl/specialization_id.hpp
/usr/include/sycl/stl_wrappers/assert.h
/usr/include/sycl/stl_wrappers/cassert
/usr/include/sycl/stl_wrappers/cmath
/usr/include/sycl/stl_wrappers/complex
/usr/include/sycl/stl_wrappers/corecrt.h
/usr/include/sycl/stl_wrappers/crtdbg.h
/usr/include/sycl/stream.hpp
/usr/include/sycl/sub_group.hpp
/usr/include/sycl/sycl.hpp
/usr/include/sycl/sycl_span.hpp
/usr/include/sycl/usm.hpp
/usr/include/sycl/usm/usm_allocator.hpp
/usr/include/sycl/usm/usm_enums.hpp
/usr/include/sycl/usm/usm_pointer_info.hpp
/usr/include/sycl/vector.hpp
/usr/include/sycl/version.hpp
/usr/include/syclcompat.hpp
/usr/include/syclcompat/atomic.hpp
/usr/include/syclcompat/defs.hpp
/usr/include/syclcompat/device.hpp
/usr/include/syclcompat/dims.hpp
/usr/include/syclcompat/group_utils.hpp
/usr/include/syclcompat/id_query.hpp
/usr/include/syclcompat/kernel.hpp
/usr/include/syclcompat/launch.hpp
/usr/include/syclcompat/launch_policy.hpp
/usr/include/syclcompat/math.hpp
/usr/include/syclcompat/memory.hpp
/usr/include/syclcompat/syclcompat.hpp
/usr/include/syclcompat/traits.hpp
/usr/include/syclcompat/util.hpp
/usr/lib/cmake/unified-runtime/unified-runtime-config-version.cmake
/usr/lib/cmake/unified-runtime/unified-runtime-config.cmake
/usr/lib/cmake/unified-runtime/unified-runtime-targets-relwithdebinfo.cmake
/usr/lib/cmake/unified-runtime/unified-runtime-targets.cmake
/usr/lib64/clang/21/include/__clang_cuda_builtin_vars.h
/usr/lib64/clang/21/include/__clang_cuda_cmath.h
/usr/lib64/clang/21/include/__clang_cuda_complex_builtins.h
/usr/lib64/clang/21/include/__clang_cuda_device_functions.h
/usr/lib64/clang/21/include/__clang_cuda_intrinsics.h
/usr/lib64/clang/21/include/__clang_cuda_libdevice_declares.h
/usr/lib64/clang/21/include/__clang_cuda_math.h
/usr/lib64/clang/21/include/__clang_cuda_math_forward_declares.h
/usr/lib64/clang/21/include/__clang_cuda_runtime_wrapper.h
/usr/lib64/clang/21/include/__clang_cuda_texture_intrinsics.h
/usr/lib64/clang/21/include/__clang_hip_cmath.h
/usr/lib64/clang/21/include/__clang_hip_libdevice_declares.h
/usr/lib64/clang/21/include/__clang_hip_math.h
/usr/lib64/clang/21/include/__clang_hip_runtime_wrapper.h
/usr/lib64/clang/21/include/__clang_hip_stdlib.h
/usr/lib64/clang/21/include/__stdarg___gnuc_va_list.h
/usr/lib64/clang/21/include/__stdarg___va_copy.h
/usr/lib64/clang/21/include/__stdarg_header_macro.h
/usr/lib64/clang/21/include/__stdarg_va_arg.h
/usr/lib64/clang/21/include/__stdarg_va_copy.h
/usr/lib64/clang/21/include/__stdarg_va_list.h
/usr/lib64/clang/21/include/__stddef_header_macro.h
/usr/lib64/clang/21/include/__stddef_max_align_t.h
/usr/lib64/clang/21/include/__stddef_null.h
/usr/lib64/clang/21/include/__stddef_nullptr_t.h
/usr/lib64/clang/21/include/__stddef_offsetof.h
/usr/lib64/clang/21/include/__stddef_ptrdiff_t.h
/usr/lib64/clang/21/include/__stddef_rsize_t.h
/usr/lib64/clang/21/include/__stddef_size_t.h
/usr/lib64/clang/21/include/__stddef_unreachable.h
/usr/lib64/clang/21/include/__stddef_wchar_t.h
/usr/lib64/clang/21/include/__stddef_wint_t.h
/usr/lib64/clang/21/include/__wmmintrin_aes.h
/usr/lib64/clang/21/include/__wmmintrin_pclmul.h
/usr/lib64/clang/21/include/adcintrin.h
/usr/lib64/clang/21/include/adxintrin.h
/usr/lib64/clang/21/include/altivec.h
/usr/lib64/clang/21/include/amdgpuintrin.h
/usr/lib64/clang/21/include/ammintrin.h
/usr/lib64/clang/21/include/amxavx512intrin.h
/usr/lib64/clang/21/include/amxbf16transposeintrin.h
/usr/lib64/clang/21/include/amxcomplexintrin.h
/usr/lib64/clang/21/include/amxcomplextransposeintrin.h
/usr/lib64/clang/21/include/amxfp16intrin.h
/usr/lib64/clang/21/include/amxfp16transposeintrin.h
/usr/lib64/clang/21/include/amxfp8intrin.h
/usr/lib64/clang/21/include/amxintrin.h
/usr/lib64/clang/21/include/amxmovrsintrin.h
/usr/lib64/clang/21/include/amxmovrstransposeintrin.h
/usr/lib64/clang/21/include/amxtf32intrin.h
/usr/lib64/clang/21/include/amxtf32transposeintrin.h
/usr/lib64/clang/21/include/amxtransposeintrin.h
/usr/lib64/clang/21/include/andes_vector.h
/usr/lib64/clang/21/include/arm64intr.h
/usr/lib64/clang/21/include/arm_acle.h
/usr/lib64/clang/21/include/arm_cmse.h
/usr/lib64/clang/21/include/arm_neon_sve_bridge.h
/usr/lib64/clang/21/include/armintr.h
/usr/lib64/clang/21/include/avx10_2_512bf16intrin.h
/usr/lib64/clang/21/include/avx10_2_512convertintrin.h
/usr/lib64/clang/21/include/avx10_2_512minmaxintrin.h
/usr/lib64/clang/21/include/avx10_2_512niintrin.h
/usr/lib64/clang/21/include/avx10_2_512satcvtdsintrin.h
/usr/lib64/clang/21/include/avx10_2_512satcvtintrin.h
/usr/lib64/clang/21/include/avx10_2bf16intrin.h
/usr/lib64/clang/21/include/avx10_2convertintrin.h
/usr/lib64/clang/21/include/avx10_2copyintrin.h
/usr/lib64/clang/21/include/avx10_2minmaxintrin.h
/usr/lib64/clang/21/include/avx10_2niintrin.h
/usr/lib64/clang/21/include/avx10_2satcvtdsintrin.h
/usr/lib64/clang/21/include/avx10_2satcvtintrin.h
/usr/lib64/clang/21/include/avx2intrin.h
/usr/lib64/clang/21/include/avx512bf16intrin.h
/usr/lib64/clang/21/include/avx512bitalgintrin.h
/usr/lib64/clang/21/include/avx512bwintrin.h
/usr/lib64/clang/21/include/avx512cdintrin.h
/usr/lib64/clang/21/include/avx512dqintrin.h
/usr/lib64/clang/21/include/avx512fintrin.h
/usr/lib64/clang/21/include/avx512fp16intrin.h
/usr/lib64/clang/21/include/avx512ifmaintrin.h
/usr/lib64/clang/21/include/avx512ifmavlintrin.h
/usr/lib64/clang/21/include/avx512vbmi2intrin.h
/usr/lib64/clang/21/include/avx512vbmiintrin.h
/usr/lib64/clang/21/include/avx512vbmivlintrin.h
/usr/lib64/clang/21/include/avx512vlbf16intrin.h
/usr/lib64/clang/21/include/avx512vlbitalgintrin.h
/usr/lib64/clang/21/include/avx512vlbwintrin.h
/usr/lib64/clang/21/include/avx512vlcdintrin.h
/usr/lib64/clang/21/include/avx512vldqintrin.h
/usr/lib64/clang/21/include/avx512vlfp16intrin.h
/usr/lib64/clang/21/include/avx512vlintrin.h
/usr/lib64/clang/21/include/avx512vlvbmi2intrin.h
/usr/lib64/clang/21/include/avx512vlvnniintrin.h
/usr/lib64/clang/21/include/avx512vlvp2intersectintrin.h
/usr/lib64/clang/21/include/avx512vnniintrin.h
/usr/lib64/clang/21/include/avx512vp2intersectintrin.h
/usr/lib64/clang/21/include/avx512vpopcntdqintrin.h
/usr/lib64/clang/21/include/avx512vpopcntdqvlintrin.h
/usr/lib64/clang/21/include/avxifmaintrin.h
/usr/lib64/clang/21/include/avxintrin.h
/usr/lib64/clang/21/include/avxneconvertintrin.h
/usr/lib64/clang/21/include/avxvnniint16intrin.h
/usr/lib64/clang/21/include/avxvnniint8intrin.h
/usr/lib64/clang/21/include/avxvnniintrin.h
/usr/lib64/clang/21/include/bmi2intrin.h
/usr/lib64/clang/21/include/bmiintrin.h
/usr/lib64/clang/21/include/builtins.h
/usr/lib64/clang/21/include/cet.h
/usr/lib64/clang/21/include/cetintrin.h
/usr/lib64/clang/21/include/cldemoteintrin.h
/usr/lib64/clang/21/include/clflushoptintrin.h
/usr/lib64/clang/21/include/clwbintrin.h
/usr/lib64/clang/21/include/clzerointrin.h
/usr/lib64/clang/21/include/cmpccxaddintrin.h
/usr/lib64/clang/21/include/cpuid.h
/usr/lib64/clang/21/include/crc32intrin.h
/usr/lib64/clang/21/include/cuda_wrappers/bits/basic_string.h
/usr/lib64/clang/21/include/cuda_wrappers/bits/shared_ptr_base.h
/usr/lib64/clang/21/include/emmintrin.h
/usr/lib64/clang/21/include/enqcmdintrin.h
/usr/lib64/clang/21/include/f16cintrin.h
/usr/lib64/clang/21/include/float.h
/usr/lib64/clang/21/include/fma4intrin.h
/usr/lib64/clang/21/include/fmaintrin.h
/usr/lib64/clang/21/include/fxsrintrin.h
/usr/lib64/clang/21/include/gfniintrin.h
/usr/lib64/clang/21/include/gpuintrin.h
/usr/lib64/clang/21/include/hexagon_circ_brev_intrinsics.h
/usr/lib64/clang/21/include/hexagon_protos.h
/usr/lib64/clang/21/include/hexagon_types.h
/usr/lib64/clang/21/include/hresetintrin.h
/usr/lib64/clang/21/include/htmintrin.h
/usr/lib64/clang/21/include/htmxlintrin.h
/usr/lib64/clang/21/include/hvx_hexagon_protos.h
/usr/lib64/clang/21/include/ia32intrin.h
/usr/lib64/clang/21/include/immintrin.h
/usr/lib64/clang/21/include/intrin.h
/usr/lib64/clang/21/include/intrin0.h
/usr/lib64/clang/21/include/inttypes.h
/usr/lib64/clang/21/include/invpcidintrin.h
/usr/lib64/clang/21/include/iso646.h
/usr/lib64/clang/21/include/keylockerintrin.h
/usr/lib64/clang/21/include/larchintrin.h
/usr/lib64/clang/21/include/lasxintrin.h
/usr/lib64/clang/21/include/limits.h
/usr/lib64/clang/21/include/llvm_libc_wrappers/assert.h
/usr/lib64/clang/21/include/llvm_libc_wrappers/ctype.h
/usr/lib64/clang/21/include/llvm_libc_wrappers/inttypes.h
/usr/lib64/clang/21/include/llvm_libc_wrappers/stdio.h
/usr/lib64/clang/21/include/llvm_libc_wrappers/stdlib.h
/usr/lib64/clang/21/include/llvm_libc_wrappers/string.h
/usr/lib64/clang/21/include/llvm_libc_wrappers/time.h
/usr/lib64/clang/21/include/llvm_offload_wrappers/__llvm_offload.h
/usr/lib64/clang/21/include/llvm_offload_wrappers/__llvm_offload_device.h
/usr/lib64/clang/21/include/llvm_offload_wrappers/__llvm_offload_host.h
/usr/lib64/clang/21/include/lsxintrin.h
/usr/lib64/clang/21/include/lwpintrin.h
/usr/lib64/clang/21/include/lzcntintrin.h
/usr/lib64/clang/21/include/mm3dnow.h
/usr/lib64/clang/21/include/mm_malloc.h
/usr/lib64/clang/21/include/mmintrin.h
/usr/lib64/clang/21/include/movdirintrin.h
/usr/lib64/clang/21/include/movrs_avx10_2_512intrin.h
/usr/lib64/clang/21/include/movrs_avx10_2intrin.h
/usr/lib64/clang/21/include/movrsintrin.h
/usr/lib64/clang/21/include/msa.h
/usr/lib64/clang/21/include/mwaitxintrin.h
/usr/lib64/clang/21/include/nmmintrin.h
/usr/lib64/clang/21/include/nvptxintrin.h
/usr/lib64/clang/21/include/opencl-c-base.h
/usr/lib64/clang/21/include/opencl-c.h
/usr/lib64/clang/21/include/openmp_wrappers/__clang_openmp_device_functions.h
/usr/lib64/clang/21/include/openmp_wrappers/complex.h
/usr/lib64/clang/21/include/openmp_wrappers/complex_cmath.h
/usr/lib64/clang/21/include/openmp_wrappers/math.h
/usr/lib64/clang/21/include/pconfigintrin.h
/usr/lib64/clang/21/include/pkuintrin.h
/usr/lib64/clang/21/include/pmmintrin.h
/usr/lib64/clang/21/include/popcntintrin.h
/usr/lib64/clang/21/include/ppc_wrappers/bmi2intrin.h
/usr/lib64/clang/21/include/ppc_wrappers/bmiintrin.h
/usr/lib64/clang/21/include/ppc_wrappers/emmintrin.h
/usr/lib64/clang/21/include/ppc_wrappers/immintrin.h
/usr/lib64/clang/21/include/ppc_wrappers/mm_malloc.h
/usr/lib64/clang/21/include/ppc_wrappers/mmintrin.h
/usr/lib64/clang/21/include/ppc_wrappers/nmmintrin.h
/usr/lib64/clang/21/include/ppc_wrappers/pmmintrin.h
/usr/lib64/clang/21/include/ppc_wrappers/smmintrin.h
/usr/lib64/clang/21/include/ppc_wrappers/tmmintrin.h
/usr/lib64/clang/21/include/ppc_wrappers/x86gprintrin.h
/usr/lib64/clang/21/include/ppc_wrappers/x86intrin.h
/usr/lib64/clang/21/include/ppc_wrappers/xmmintrin.h
/usr/lib64/clang/21/include/prfchiintrin.h
/usr/lib64/clang/21/include/prfchwintrin.h
/usr/lib64/clang/21/include/ptrauth.h
/usr/lib64/clang/21/include/ptwriteintrin.h
/usr/lib64/clang/21/include/raointintrin.h
/usr/lib64/clang/21/include/rdpruintrin.h
/usr/lib64/clang/21/include/rdseedintrin.h
/usr/lib64/clang/21/include/riscv_bitmanip.h
/usr/lib64/clang/21/include/riscv_corev_alu.h
/usr/lib64/clang/21/include/riscv_crypto.h
/usr/lib64/clang/21/include/riscv_ntlh.h
/usr/lib64/clang/21/include/rtmintrin.h
/usr/lib64/clang/21/include/s390intrin.h
/usr/lib64/clang/21/include/serializeintrin.h
/usr/lib64/clang/21/include/sgxintrin.h
/usr/lib64/clang/21/include/sha512intrin.h
/usr/lib64/clang/21/include/shaintrin.h
/usr/lib64/clang/21/include/sifive_vector.h
/usr/lib64/clang/21/include/sm3intrin.h
/usr/lib64/clang/21/include/sm4evexintrin.h
/usr/lib64/clang/21/include/sm4intrin.h
/usr/lib64/clang/21/include/smmintrin.h
/usr/lib64/clang/21/include/stdalign.h
/usr/lib64/clang/21/include/stdarg.h
/usr/lib64/clang/21/include/stdatomic.h
/usr/lib64/clang/21/include/stdbool.h
/usr/lib64/clang/21/include/stdckdint.h
/usr/lib64/clang/21/include/stddef.h
/usr/lib64/clang/21/include/stdint.h
/usr/lib64/clang/21/include/stdnoreturn.h
/usr/lib64/clang/21/include/tbmintrin.h
/usr/lib64/clang/21/include/tgmath.h
/usr/lib64/clang/21/include/tmmintrin.h
/usr/lib64/clang/21/include/tsxldtrkintrin.h
/usr/lib64/clang/21/include/uintrintrin.h
/usr/lib64/clang/21/include/unwind.h
/usr/lib64/clang/21/include/usermsrintrin.h
/usr/lib64/clang/21/include/vadefs.h
/usr/lib64/clang/21/include/vaesintrin.h
/usr/lib64/clang/21/include/varargs.h
/usr/lib64/clang/21/include/vecintrin.h
/usr/lib64/clang/21/include/velintrin.h
/usr/lib64/clang/21/include/velintrin_approx.h
/usr/lib64/clang/21/include/velintrin_gen.h
/usr/lib64/clang/21/include/vpclmulqdqintrin.h
/usr/lib64/clang/21/include/waitpkgintrin.h
/usr/lib64/clang/21/include/wasm_simd128.h
/usr/lib64/clang/21/include/wbnoinvdintrin.h
/usr/lib64/clang/21/include/wmmintrin.h
/usr/lib64/clang/21/include/x86gprintrin.h
/usr/lib64/clang/21/include/x86intrin.h
/usr/lib64/clang/21/include/xmmintrin.h
/usr/lib64/clang/21/include/xopintrin.h
/usr/lib64/clang/21/include/xsavecintrin.h
/usr/lib64/clang/21/include/xsaveintrin.h
/usr/lib64/clang/21/include/xsaveoptintrin.h
/usr/lib64/clang/21/include/xsavesintrin.h
/usr/lib64/clang/21/include/xtestintrin.h
/usr/lib64/clang/21/include/yvals_core.h
/usr/lib64/clang/21/include/zos_wrappers/builtins.h
/usr/lib64/libsycl-preview.so
/usr/lib64/libsycl.so
/usr/lib64/libur_adapter_level_zero.so
/usr/lib64/libur_adapter_level_zero_v2.so
/usr/lib64/libur_loader.so
/usr/lib64/pkgconfig/libur_loader.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libLTO.so.21.0-dpcpp
/usr/lib64/libRemarks.so.21.0-dpcpp
/usr/lib64/libclang-cpp.so.21.0-dpcpp
/usr/lib64/libclang.so.21.0-dpcpp
/usr/lib64/libclang.so.21.0.0-dpcpp
/usr/lib64/libsycl-preview.so.8
/usr/lib64/libsycl-preview.so.8.0.0-0
/usr/lib64/libsycl.so.8
/usr/lib64/libsycl.so.8.0.0-0
/usr/lib64/libsycl.so.8.0.0-0-gdb.py
/usr/lib64/libur_adapter_level_zero.so.0
/usr/lib64/libur_adapter_level_zero.so.0.12.0
/usr/lib64/libur_adapter_level_zero_v2.so.0
/usr/lib64/libur_adapter_level_zero_v2.so.0.12.0
/usr/lib64/libur_loader.so.0
/usr/lib64/libur_loader.so.0.12.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/dpcpp-compiler/069917c4e281e9c890d84d0e4c081e295741a146
/usr/share/package-licenses/dpcpp-compiler/0884cb5458dcea3aeca8bf62ff4638f145da9080
/usr/share/package-licenses/dpcpp-compiler/1020f0e93b771814d86731da816eb9f22f2ab7b4
/usr/share/package-licenses/dpcpp-compiler/11156021d878bfcbdf2563b4f65db32b4d9f92a3
/usr/share/package-licenses/dpcpp-compiler/19ab4d0ca881c5cb0eb16b70c76c89d854aa291e
/usr/share/package-licenses/dpcpp-compiler/205f35d8fa25bc2a6d6d9eb79eb06d4fb33d9be4
/usr/share/package-licenses/dpcpp-compiler/218fc8c15534e8840cbff5801582c450c97869ab
/usr/share/package-licenses/dpcpp-compiler/24ebc22b6e51adf8b01ec0340b69fc7dd2178c1d
/usr/share/package-licenses/dpcpp-compiler/2858f1aaa0df159c19da9047793c176ded5fde73
/usr/share/package-licenses/dpcpp-compiler/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/dpcpp-compiler/364c81eae824ba65626c2442274579712dc24708
/usr/share/package-licenses/dpcpp-compiler/385649e7c18da3a07cfbd6679eebd0bca1c698c9
/usr/share/package-licenses/dpcpp-compiler/38c74b79370d3a6a99c7b80c3d48e6caaf0636f2
/usr/share/package-licenses/dpcpp-compiler/45c2429b5881295597e96c81fc50f7b8a42e769f
/usr/share/package-licenses/dpcpp-compiler/512260ce8ee598c5985f35ea4d8834e6c35f4958
/usr/share/package-licenses/dpcpp-compiler/59a8ba331dede4d94bd654ac645e8d27463662f4
/usr/share/package-licenses/dpcpp-compiler/5a2314153eadadc69258a9429104cd11804ea304
/usr/share/package-licenses/dpcpp-compiler/5a64e4783751612e7603131e11bb81655bcb2b4e
/usr/share/package-licenses/dpcpp-compiler/5d941660d20397d61e58adb87e2dd05fa60828ef
/usr/share/package-licenses/dpcpp-compiler/5feeec1755c1a12a9ade79c0db7ce0dd05baf119
/usr/share/package-licenses/dpcpp-compiler/5ffa2266f82fe7453a84cc81e06ef01fa4b451d5
/usr/share/package-licenses/dpcpp-compiler/689ec0681815ecc32bee639c68e7740add7bd301
/usr/share/package-licenses/dpcpp-compiler/6b655b0685aa7ee33fa1e02103b3bf22ed06e099
/usr/share/package-licenses/dpcpp-compiler/72c865be698cefc46549ed61e279f98432364fca
/usr/share/package-licenses/dpcpp-compiler/7b75a5471af8b3d49e60df0a5d72f95ea8214231
/usr/share/package-licenses/dpcpp-compiler/7bb7e3e90405caf5d2dfb4bc5c9a4e52c836d66d
/usr/share/package-licenses/dpcpp-compiler/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/dpcpp-compiler/7e042c41bcb0960a16525d88d8308cf7ee444463
/usr/share/package-licenses/dpcpp-compiler/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/dpcpp-compiler/833029af4fec08f548eee8861ee73e8ef9395b2b
/usr/share/package-licenses/dpcpp-compiler/85c0f2884378413881b4d3e27fc24b220f71889b
/usr/share/package-licenses/dpcpp-compiler/8737af83de0d40386dca9a4abe2b6faa83cb4750
/usr/share/package-licenses/dpcpp-compiler/8af372ad1edbed2cfaf0e79d25f7136ec6e55b47
/usr/share/package-licenses/dpcpp-compiler/8d3b142938f83e7045951089b52676a5605eee37
/usr/share/package-licenses/dpcpp-compiler/8f178caf2a2d6e6c711a30da69077572df356cf6
/usr/share/package-licenses/dpcpp-compiler/a1691103171dc1d21cfa85f1d4809a16b9f1367f
/usr/share/package-licenses/dpcpp-compiler/a6695de026d58b7d5759b497587ccc941f90e991
/usr/share/package-licenses/dpcpp-compiler/af07f365643f841c69797e9059b66f0bd847f1cd
/usr/share/package-licenses/dpcpp-compiler/b52b5d7278f63f47262b5cbf5ae7762073bbf885
/usr/share/package-licenses/dpcpp-compiler/bfc2b026231b7aca6db90de3471e76dbb94e9c24
/usr/share/package-licenses/dpcpp-compiler/c01c212bdf3925189f673e2081b44094023860ea
/usr/share/package-licenses/dpcpp-compiler/d255f01e9636b0346a9650d2ba50692a03e8938e
/usr/share/package-licenses/dpcpp-compiler/d5c5d1f2a2c34ddf445bd787517a4423a2fd5b1b
/usr/share/package-licenses/dpcpp-compiler/d79062af10a33188d4a74d976323845a2cf9023d
/usr/share/package-licenses/dpcpp-compiler/e296859078301a417e5364eac616b0ec020d088a
/usr/share/package-licenses/dpcpp-compiler/e3cccabb67bd491a643d32a7d2b65b49836e626d
/usr/share/package-licenses/dpcpp-compiler/f4359b9da55a3b9e4d9513eb79cacf125fb49e7b
/usr/share/package-licenses/dpcpp-compiler/fccfc2fce8f47edefc797bdc3835ddd9a614ccd5
