#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v3
# autospec commit: ab27b0e7ad12
#
Name     : dpcpp-compiler
Version  : 2023.08.31
Release  : 9
URL      : https://github.com/intel/llvm/archive/nightly-2023-08-31/llvm-nightly-2023-08-31.tar.gz
Source0  : https://github.com/intel/llvm/archive/nightly-2023-08-31/llvm-nightly-2023-08-31.tar.gz
Source1  : https://github.com/KhronosGroup/OpenCL-Headers/archive/v2023.04.17/opencl-headers-2023.04.17.tar.gz
Source2  : https://github.com/KhronosGroup/OpenCL-ICD-Loader/archive/v2023.04.17/opencl-icd-loader-2023.04.17.tar.gz
Source3  : https://github.com/boostorg/assert/archive/boost-1.83.0/assert-boost-1.83.0.tar.gz
Source4  : https://github.com/boostorg/config/archive/boost-1.83.0/config-boost-1.83.0.tar.gz
Source5  : https://github.com/boostorg/container_hash/archive/boost-1.83.0/container_hash-boost-1.83.0.tar.gz
Source6  : https://github.com/boostorg/core/archive/boost-1.83.0/core-boost-1.83.0.tar.gz
Source7  : https://github.com/boostorg/describe/archive/boost-1.83.0/describe-boost-1.83.0.tar.gz
Source8  : https://github.com/boostorg/move/archive/boost-1.83.0/move-boost-1.83.0.tar.gz
Source9  : https://github.com/boostorg/mp11/archive/boost-1.83.0/mp11-boost-1.83.0.tar.gz
Source10  : https://github.com/boostorg/predef/archive/boost-1.83.0/predef-boost-1.83.0.tar.gz
Source11  : https://github.com/boostorg/preprocessor/archive/boost-1.83.0/preprocessor-boost-1.83.0.tar.gz
Source12  : https://github.com/boostorg/static_assert/archive/boost-1.83.0/static_assert-boost-1.83.0.tar.gz
Source13  : https://github.com/boostorg/throw_exception/archive/boost-1.83.0/throw_exception-boost-1.83.0.tar.gz
Source14  : https://github.com/boostorg/tuple/archive/boost-1.83.0/tuple-boost-1.83.0.tar.gz
Source15  : https://github.com/boostorg/type_traits/archive/boost-1.83.0/type_traits-boost-1.83.0.tar.gz
Source16  : https://github.com/boostorg/unordered/archive/boost-1.83.0/unordered-boost-1.83.0.tar.gz
Source17  : https://github.com/intel/vc-intrinsics/archive/v0.13.0/vc-intrinsics-0.13.0.tar.gz
Source18  : https://github.com/oneapi-src/unified-runtime/archive/weekly-2023-08-18/unified-runtime-weekly-2023-08-18.tar.gz
Summary  : Library requirements of the OpenCL C programming language
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause BSL-1.0 ISC MIT MPL-2.0 NCSA
Requires: dpcpp-compiler-bin = %{version}-%{release}
Requires: dpcpp-compiler-data = %{version}-%{release}
Requires: dpcpp-compiler-lib = %{version}-%{release}
Requires: dpcpp-compiler-license = %{version}-%{release}
BuildRequires : SPIRV-Headers-dev
BuildRequires : Vulkan-Headers-dev Vulkan-Loader-dev Vulkan-Tools
BuildRequires : Z3-dev
BuildRequires : buildreq-cmake
BuildRequires : cmake
BuildRequires : curl-dev
BuildRequires : doxygen
BuildRequires : gcc-staticdev
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : googletest-dev
BuildRequires : level-zero-dev
BuildRequires : libxml2-dev
BuildRequires : llvm-bin
BuildRequires : llvm-dev
BuildRequires : lua-dev
BuildRequires : ncurses-dev
BuildRequires : ninja
BuildRequires : perl
BuildRequires : pkg-config
BuildRequires : pkgconfig(OpenCL-Headers)
BuildRequires : pkgconfig(SPIRV-Headers)
BuildRequires : pkgconfig(SPIRV-Tools)
BuildRequires : pkgconfig(level-zero)
BuildRequires : pkgconfig(libedit)
BuildRequires : pkgconfig(libffi)
BuildRequires : protobuf-dev
BuildRequires : pypi(pybind11)
BuildRequires : python3-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Add-missing-sycl-include-path.patch
Patch2: backport-Guard-removed-typed-pointer-enum-within-version-macro.patch

%description
Files in this directory:
o .lldbinit:
An example lldb init file that imports the binutils.py module and adds the
following commands: 'itob' and 'utob'.

%package bin
Summary: bin components for the dpcpp-compiler package.
Group: Binaries
Requires: dpcpp-compiler-data = %{version}-%{release}
Requires: dpcpp-compiler-license = %{version}-%{release}

%description bin
bin components for the dpcpp-compiler package.


%package data
Summary: data components for the dpcpp-compiler package.
Group: Data

%description data
data components for the dpcpp-compiler package.


%package dev
Summary: dev components for the dpcpp-compiler package.
Group: Development
Requires: dpcpp-compiler-lib = %{version}-%{release}
Requires: dpcpp-compiler-bin = %{version}-%{release}
Requires: dpcpp-compiler-data = %{version}-%{release}
Provides: dpcpp-compiler-devel = %{version}-%{release}
Requires: dpcpp-compiler = %{version}-%{release}

%description dev
dev components for the dpcpp-compiler package.


%package lib
Summary: lib components for the dpcpp-compiler package.
Group: Libraries
Requires: dpcpp-compiler-data = %{version}-%{release}
Requires: dpcpp-compiler-license = %{version}-%{release}

%description lib
lib components for the dpcpp-compiler package.


%package license
Summary: license components for the dpcpp-compiler package.
Group: Default

%description license
license components for the dpcpp-compiler package.


%prep
%setup -q -n llvm-nightly-2023-08-31
cd %{_builddir}
tar xf %{_sourcedir}/opencl-headers-2023.04.17.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/opencl-icd-loader-2023.04.17.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/assert-boost-1.83.0.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/config-boost-1.83.0.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/container_hash-boost-1.83.0.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/core-boost-1.83.0.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/describe-boost-1.83.0.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/move-boost-1.83.0.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/predef-boost-1.83.0.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/preprocessor-boost-1.83.0.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/static_assert-boost-1.83.0.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/throw_exception-boost-1.83.0.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/tuple-boost-1.83.0.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/type_traits-boost-1.83.0.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/unordered-boost-1.83.0.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/mp11-boost-1.83.0.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/vc-intrinsics-0.13.0.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/unified-runtime-weekly-2023-08-18.tar.gz
cd %{_builddir}/llvm-nightly-2023-08-31
mkdir -p ../opencl-headers
cp -r %{_builddir}/OpenCL-Headers-2023.04.17/* %{_builddir}/llvm-nightly-2023-08-31/../opencl-headers
mkdir -p ../ocl-icd-src
cp -r %{_builddir}/OpenCL-ICD-Loader-2023.04.17/* %{_builddir}/llvm-nightly-2023-08-31/../ocl-icd-src
mkdir -p ../boost_assert
cp -r %{_builddir}/assert-boost-1.83.0/* %{_builddir}/llvm-nightly-2023-08-31/../boost_assert
mkdir -p ../boost_config
cp -r %{_builddir}/config-boost-1.83.0/* %{_builddir}/llvm-nightly-2023-08-31/../boost_config
mkdir -p ../boost_container_hash
cp -r %{_builddir}/container_hash-boost-1.83.0/* %{_builddir}/llvm-nightly-2023-08-31/../boost_container_hash
mkdir -p ../boost_core
cp -r %{_builddir}/core-boost-1.83.0/* %{_builddir}/llvm-nightly-2023-08-31/../boost_core
mkdir -p ../boost_describe
cp -r %{_builddir}/describe-boost-1.83.0/* %{_builddir}/llvm-nightly-2023-08-31/../boost_describe
mkdir -p ../boost_move
cp -r %{_builddir}/move-boost-1.83.0/* %{_builddir}/llvm-nightly-2023-08-31/../boost_move
mkdir -p ../boost_predef
cp -r %{_builddir}/predef-boost-1.83.0/* %{_builddir}/llvm-nightly-2023-08-31/../boost_predef
mkdir -p ../boost_preprocessor
cp -r %{_builddir}/preprocessor-boost-1.83.0/* %{_builddir}/llvm-nightly-2023-08-31/../boost_preprocessor
mkdir -p ../boost_static_assert
cp -r %{_builddir}/static_assert-boost-1.83.0/* %{_builddir}/llvm-nightly-2023-08-31/../boost_static_assert
mkdir -p ../boost_throw_exception
cp -r %{_builddir}/throw_exception-boost-1.83.0/* %{_builddir}/llvm-nightly-2023-08-31/../boost_throw_exception
mkdir -p ../boost_tuple
cp -r %{_builddir}/tuple-boost-1.83.0/* %{_builddir}/llvm-nightly-2023-08-31/../boost_tuple
mkdir -p ../boost_type_traits
cp -r %{_builddir}/type_traits-boost-1.83.0/* %{_builddir}/llvm-nightly-2023-08-31/../boost_type_traits
mkdir -p ../boost_unordered
cp -r %{_builddir}/unordered-boost-1.83.0/* %{_builddir}/llvm-nightly-2023-08-31/../boost_unordered
mkdir -p ../boost_mp11
cp -r %{_builddir}/mp11-boost-1.83.0/* %{_builddir}/llvm-nightly-2023-08-31/../boost_mp11
mkdir -p ../vc-intrinsics
cp -r %{_builddir}/vc-intrinsics-0.13.0/* %{_builddir}/llvm-nightly-2023-08-31/../vc-intrinsics
mkdir -p ../unified-runtime
cp -r %{_builddir}/unified-runtime-weekly-2023-08-18/* %{_builddir}/llvm-nightly-2023-08-31/../unified-runtime
%patch -P 1 -p1
%patch -P 2 -d ../vc-intrinsics -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1705116285
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%cmake ../llvm -DLLVM_VERSION_SUFFIX=-dpcpp \
-DBOOST_ASSERT_SOURCE_DIR=%{_builddir}/boost_assert \
-DBOOST_CONFIG_SOURCE_DIR=%{_builddir}/boost_config \
-DBOOST_CONTAINER_HASH_SOURCE_DIR=%{_builddir}/boost_container_hash \
-DBOOST_CORE_SOURCE_DIR=%{_builddir}/boost_core \
-DBOOST_DESCRIBE_SOURCE_DIR=%{_builddir}/boost_describe \
-DBOOST_MOVE_SOURCE_DIR=%{_builddir}/boost_move \
-DBOOST_MP11_SOURCE_DIR=%{_builddir}/boost_mp11 \
-DBOOST_PREDEF_SOURCE_DIR=%{_builddir}/boost_predef \
-DBOOST_PREPROCESSOR_SOURCE_DIR=%{_builddir}/boost_preprocessor \
-DBOOST_STATIC_ASSERT_SOURCE_DIR=%{_builddir}/boost_static_assert \
-DBOOST_THROW_EXCEPTION_SOURCE_DIR=%{_builddir}/boost_throw_exception \
-DBOOST_TUPLE_SOURCE_DIR=%{_builddir}/boost_tuple \
-DBOOST_TYPE_TRAITS_SOURCE_DIR=%{_builddir}/boost_type_traits \
-DBOOST_UNORDERED_SOURCE_DIR=%{_builddir}/boost_unordered \
-DBUG_REPORT_URL=https://github.com/intel/llvm/issues \
-DBUILD_SHARED_LIBS=OFF \
-DFETCHCONTENT_SOURCE_DIR_OCL-HEADERS=%{_builddir}/opencl-headers \
-DFETCHCONTENT_SOURCE_DIR_OCL-ICD=%{_builddir}/ocl-icd-src \
-DFETCHCONTENT_SOURCE_DIR_UNIFIED-RUNTIME=%{_builddir}/unified-runtime \
-DFETCHCONTENT_SOURCE_DIR_VC-INTRINSICS=%{_builddir}/vc-intrinsics \
-DLEVEL_ZERO_INCLUDE_DIR=/usr/include/level_zero \
-DLEVEL_ZERO_LIBRARY=/usr/lib64/libze_loader.so.1 \
-DLIBCLC_GENERATE_REMANGLED_VARIANTS=OFF \
-DLIBCLC_TARGETS_TO_BUILD= \
-DLLVM_BUILD_TOOLS=ON \
-DLLVM_ENABLE_ASSERTIONS=ON \
-DLLVM_ENABLE_DOXYGEN=OFF \
-DLLVM_ENABLE_LLD=OFF \
-DLLVM_ENABLE_PROJECTS='clang;sycl;llvm-spirv;opencl;xpti;xptifw;libdevice;sycl-fusion' \
-DLLVM_ENABLE_SPHINX=OFF \
-DLLVM_EXTERNAL_LLVM_SPIRV_SOURCE_DIR=../llvm-spirv \
-DLLVM_EXTERNAL_PROJECTS='sycl;llvm-spirv;opencl;xpti;xptifw;libdevice;sycl-fusion' \
-DLLVM_EXTERNAL_SPIRV_HEADERS_SOURCE_DIR=/usr/include/spirv \
-DLLVM_EXTERNAL_SYCL_FUSION_SOURCE_DIR=../sycl-fusion \
-DLLVM_EXTERNAL_XPTIFW_SOURCE_DIR=../xptifw \
-DLLVM_TARGETS_TO_BUILD=X86 \
-DOpenCL_INCLUDE_DIR=/usr/include \
-DSYCL_BUILD_PI_HIP_PLATFORM=AMD \
-DSYCL_CLANG_EXTRA_FLAGS='-I../sycl/include' \
-DSYCL_ENABLE_KERNEL_FUSION=ON \
-DSYCL_ENABLE_PLUGINS='level_zero;opencl' \
-DSYCL_ENABLE_WERROR=OFF \
-DSYCL_ENABLE_XPTI_TRACING=ON \
-DSYCL_INCLUDE_TESTS=ON \
-DXPTI_ENABLE_WERROR=OFF
make  %{?_smp_mflags}  CPLUS_INCLUDE_PATH="/usr/include/c++/13:/usr/include/c++/13/x86_64-generic-linux/" \
all \
libsycldevice-spv \
libsycldevice-obj
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1705116285
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/dpcpp-compiler
cp %{_builddir}/OpenCL-Headers-2023.04.17/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/OpenCL-ICD-Loader-2023.04.17/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/llvm-nightly-2023-08-31/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/af07f365643f841c69797e9059b66f0bd847f1cd || :
cp %{_builddir}/llvm-nightly-2023-08-31/bolt/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/af07f365643f841c69797e9059b66f0bd847f1cd || :
cp %{_builddir}/llvm-nightly-2023-08-31/clang-tools-extra/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/a1691103171dc1d21cfa85f1d4809a16b9f1367f || :
cp %{_builddir}/llvm-nightly-2023-08-31/clang/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/a1691103171dc1d21cfa85f1d4809a16b9f1367f || :
cp %{_builddir}/llvm-nightly-2023-08-31/clang/tools/clang-format-vs/ClangFormat/license.txt %{buildroot}/usr/share/package-licenses/dpcpp-compiler/b5d4ab4d1191e592c03310adfbe90d99a46bf9d7 || :
cp %{_builddir}/llvm-nightly-2023-08-31/compiler-rt/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/f4359b9da55a3b9e4d9513eb79cacf125fb49e7b || :
cp %{_builddir}/llvm-nightly-2023-08-31/cross-project-tests/debuginfo-tests/dexter/LICENSE.txt %{buildroot}/usr/share/package-licenses/dpcpp-compiler/af07f365643f841c69797e9059b66f0bd847f1cd || :
cp %{_builddir}/llvm-nightly-2023-08-31/flang/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/85c0f2884378413881b4d3e27fc24b220f71889b || :
cp %{_builddir}/llvm-nightly-2023-08-31/libc/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/a1691103171dc1d21cfa85f1d4809a16b9f1367f || :
cp %{_builddir}/llvm-nightly-2023-08-31/libclc/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/8737af83de0d40386dca9a4abe2b6faa83cb4750 || :
cp %{_builddir}/llvm-nightly-2023-08-31/libcxx/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/7b75a5471af8b3d49e60df0a5d72f95ea8214231 || :
cp %{_builddir}/llvm-nightly-2023-08-31/libcxxabi/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/11156021d878bfcbdf2563b4f65db32b4d9f92a3 || :
cp %{_builddir}/llvm-nightly-2023-08-31/libunwind/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/d79062af10a33188d4a74d976323845a2cf9023d || :
cp %{_builddir}/llvm-nightly-2023-08-31/lld/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/6b655b0685aa7ee33fa1e02103b3bf22ed06e099 || :
cp %{_builddir}/llvm-nightly-2023-08-31/lldb/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/8af372ad1edbed2cfaf0e79d25f7136ec6e55b47 || :
cp %{_builddir}/llvm-nightly-2023-08-31/lldb/third_party/Python/module/pexpect-4.6/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/5a99e7077ee89ba92fb3f584855e8970096cd5dc || :
cp %{_builddir}/llvm-nightly-2023-08-31/lldb/third_party/Python/module/ptyprocess-0.6.0/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/db1f866b29c6a191752c7c5924b7572cdbc47c34 || :
cp %{_builddir}/llvm-nightly-2023-08-31/llvm-spirv/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/8f178caf2a2d6e6c711a30da69077572df356cf6 || :
cp %{_builddir}/llvm-nightly-2023-08-31/llvm/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/af07f365643f841c69797e9059b66f0bd847f1cd || :
cp %{_builddir}/llvm-nightly-2023-08-31/llvm/include/llvm/Support/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/5feeec1755c1a12a9ade79c0db7ce0dd05baf119 || :
cp %{_builddir}/llvm-nightly-2023-08-31/llvm/lib/Support/BLAKE3/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/bfc2b026231b7aca6db90de3471e76dbb94e9c24 || :
cp %{_builddir}/llvm-nightly-2023-08-31/llvm/test/YAMLParser/LICENSE.txt %{buildroot}/usr/share/package-licenses/dpcpp-compiler/c01c212bdf3925189f673e2081b44094023860ea || :
cp %{_builddir}/llvm-nightly-2023-08-31/llvm/utils/lit/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/af07f365643f841c69797e9059b66f0bd847f1cd || :
cp %{_builddir}/llvm-nightly-2023-08-31/mlir/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/85c0f2884378413881b4d3e27fc24b220f71889b || :
cp %{_builddir}/llvm-nightly-2023-08-31/openmp/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/e3cccabb67bd491a643d32a7d2b65b49836e626d || :
cp %{_builddir}/llvm-nightly-2023-08-31/openmp/runtime/src/thirdparty/ittnotify/LICENSE.txt %{buildroot}/usr/share/package-licenses/dpcpp-compiler/59a8ba331dede4d94bd654ac645e8d27463662f4 || :
cp %{_builddir}/llvm-nightly-2023-08-31/polly/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/8d3b142938f83e7045951089b52676a5605eee37 || :
cp %{_builddir}/llvm-nightly-2023-08-31/polly/lib/External/isl/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/45c2429b5881295597e96c81fc50f7b8a42e769f || :
cp %{_builddir}/llvm-nightly-2023-08-31/polly/lib/External/isl/imath/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/385649e7c18da3a07cfbd6679eebd0bca1c698c9 || :
cp %{_builddir}/llvm-nightly-2023-08-31/pstl/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/72c865be698cefc46549ed61e279f98432364fca || :
cp %{_builddir}/llvm-nightly-2023-08-31/sycl/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/2858f1aaa0df159c19da9047793c176ded5fde73 || :
cp %{_builddir}/llvm-nightly-2023-08-31/third-party/benchmark/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/llvm-nightly-2023-08-31/third-party/unittest/googlemock/LICENSE.txt %{buildroot}/usr/share/package-licenses/dpcpp-compiler/5a2314153eadadc69258a9429104cd11804ea304 || :
cp %{_builddir}/llvm-nightly-2023-08-31/third-party/unittest/googletest/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/5a2314153eadadc69258a9429104cd11804ea304 || :
cp %{_builddir}/llvm-nightly-2023-08-31/xptifw/basic_test/external/LICENSE.txt %{buildroot}/usr/share/package-licenses/dpcpp-compiler/5ffa2266f82fe7453a84cc81e06ef01fa4b451d5 || :
cp %{_builddir}/move-boost-1.83.0/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/unified-runtime-weekly-2023-08-18/LICENSE.TXT %{buildroot}/usr/share/package-licenses/dpcpp-compiler/5a64e4783751612e7603131e11bb81655bcb2b4e || :
cp %{_builddir}/unordered-boost-1.83.0/LICENSE %{buildroot}/usr/share/package-licenses/dpcpp-compiler/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/vc-intrinsics-0.13.0/LICENSE.md %{buildroot}/usr/share/package-licenses/dpcpp-compiler/723eea2469244a92b3e3461b79c3e848ce058cc6 || :
pushd clr-build
%make_install
popd
## Remove excluded files
rm -f %{buildroot}*/usr/lib/libLTO.so
rm -f %{buildroot}*/usr/lib/libRemarks.so
rm -f %{buildroot}*/usr/lib/libclang-cpp.so
rm -f %{buildroot}*/usr/lib/libclang.so
rm -f %{buildroot}*/usr/lib64/libLTO.so
rm -f %{buildroot}*/usr/lib64/libRemarks.so
rm -f %{buildroot}*/usr/lib64/libclang-cpp.so
rm -f %{buildroot}*/usr/lib64/libclang.so
rm -f %{buildroot}*/usr/lib64/pkgconfig/LLVMSPIRVLib.pc
rm -f %{buildroot}*/usr/libexec/analyze-c++
rm -f %{buildroot}*/usr/libexec/analyze-cc
rm -f %{buildroot}*/usr/libexec/c++-analyzer
rm -f %{buildroot}*/usr/libexec/ccc-analyzer
rm -f %{buildroot}*/usr/libexec/intercept-c++
rm -f %{buildroot}*/usr/libexec/intercept-cc
rm -f %{buildroot}*/usr/share/clang/bash-autocomplete.sh
rm -f %{buildroot}*/usr/share/clang/clang-format-bbedit.applescript
rm -f %{buildroot}*/usr/share/clang/clang-format-diff.py
rm -f %{buildroot}*/usr/share/clang/clang-format-sublime.py
rm -f %{buildroot}*/usr/share/clang/clang-format.el
rm -f %{buildroot}*/usr/share/clang/clang-format.py
rm -f %{buildroot}*/usr/share/clang/clang-rename.el
rm -f %{buildroot}*/usr/share/clang/clang-rename.py
rm -f %{buildroot}*/usr/share/man/man1/scan-build.1
rm -f %{buildroot}*/usr/share/opt-viewer/opt-diff.py
rm -f %{buildroot}*/usr/share/opt-viewer/opt-stats.py
rm -f %{buildroot}*/usr/share/opt-viewer/opt-viewer.py
rm -f %{buildroot}*/usr/share/opt-viewer/optpmap.py
rm -f %{buildroot}*/usr/share/opt-viewer/optrecord.py
rm -f %{buildroot}*/usr/share/opt-viewer/style.css
rm -f %{buildroot}*/usr/share/scan-build/scanview.css
rm -f %{buildroot}*/usr/share/scan-build/sorttable.js
rm -f %{buildroot}*/usr/share/scan-view/Reporter.py
rm -f %{buildroot}*/usr/share/scan-view/ScanView.py
rm -f %{buildroot}*/usr/share/scan-view/bugcatcher.ico
rm -f %{buildroot}*/usr/share/scan-view/startfile.py
rm -f %{buildroot}*/usr/lib64/libOpenCL.so
rm -f %{buildroot}*/usr/lib64/libOpenCL.so.1
rm -f %{buildroot}*/usr/lib64/libOpenCL.so.1
rm -f %{buildroot}*/usr/lib64/libOpenCL.so.1.2
rm -f %{buildroot}*/usr/lib64/libOpenCL.so.1.2
rm -f %{buildroot}*/usr/lib64/pkgconfig/OpenCL.pc
rm -f %{buildroot}*/usr/include/CL/cl.h
rm -f %{buildroot}*/usr/include/CL/cl_d3d10.h
rm -f %{buildroot}*/usr/include/CL/cl_d3d11.h
rm -f %{buildroot}*/usr/include/CL/cl_dx9_media_sharing.h
rm -f %{buildroot}*/usr/include/CL/cl_dx9_media_sharing_intel.h
rm -f %{buildroot}*/usr/include/CL/cl_egl.h
rm -f %{buildroot}*/usr/include/CL/cl_ext.h
rm -f %{buildroot}*/usr/include/CL/cl_ext_intel.h
rm -f %{buildroot}*/usr/include/CL/cl_gl.h
rm -f %{buildroot}*/usr/include/CL/cl_gl_ext.h
rm -f %{buildroot}*/usr/include/CL/cl_half.h
rm -f %{buildroot}*/usr/include/CL/cl_half.h
rm -f %{buildroot}*/usr/include/CL/cl_icd.h
rm -f %{buildroot}*/usr/include/CL/cl_layer.h
rm -f %{buildroot}*/usr/include/CL/cl_platform.h
rm -f %{buildroot}*/usr/include/CL/cl_va_api_media_sharing_intel.h
rm -f %{buildroot}*/usr/include/CL/cl_version.h
rm -f %{buildroot}*/usr/include/CL/opencl.h
rm -f %{buildroot}*/usr/lib64/pkgconfig/OpenCL-Headers.pc
rm -f %{buildroot}*/usr/share/cmake/OpenCLHeaders/OpenCLHeadersConfig.cmake
rm -f %{buildroot}*/usr/share/cmake/OpenCLHeaders/OpenCLHeadersConfigVersion.cmake
rm -f %{buildroot}*/usr/share/cmake/OpenCLHeaders/OpenCLHeadersTargets.cmake
## install_append content
# remove libomptarget.rtl.amdgpu.so for now
# it is built using rpath and wants to be in the wrong path
# rm -f %{buildroot}/usr/lib/libomptarget.rtl.amdgpu.so

# Remove files that should come from the main llvm package
# rm -rf %{buildroot}/usr/include
# rm -fr %{buildroot}/usr/lib/libear
# rm -fr %{buildroot}/usr/lib/libscanbuild
# rm -fr %{buildroot}/usr/lib/python3.11
# rm -rf %{buildroot}/usr/lib32/*.a
# rm -rf %{buildroot}/usr/lib32/*.so
# rm -rf %{buildroot}/usr/lib32/cmake
# rm -rf %{buildroot}/usr/lib32/pkgconfig
# rm -rf %{buildroot}/usr/lib64/*.a
# rm -rf %{buildroot}/usr/lib64/*.so
# rm -rf %{buildroot}/usr/lib64/cmake
# rm -rf %{buildroot}/usr/lib64/pkgconfig
# rm -rf %{buildroot}/usr/libexec

# Remove all the includes *except* those for SYCL
find %{buildroot}/usr/include '(' -type f -a '!' -ipath '*sycl*' ')' -exec rm {} +

# Cleanup empty directories
find %{buildroot}/usr/include -type d -empty -exec rmdir {} +

# mv %{buildroot}/usr/share/package-licenses %{buildroot}/usr/
# rm -rf %{buildroot}/usr/share/*
# mv %{buildroot}/usr/package-licenses %{buildroot}/usr/share

# Rename the tools to have a versioned suffix and symlink back
pushd %{buildroot}/usr
FULL_VERSION=dpcpp-%{version}
mkdir -p lib64/clang/$FULL_VERSION/bin
mv bin/* lib64/clang/$FULL_VERSION/bin
for f in lib64/clang/$FULL_VERSION/bin/*; do
case "$f" in
*-$VERSION)
# Already versioned, leave it alone
continue
;;
esac
ln -s ../$f bin/${f##*/}-dpcpp
done

# libclang-cpp auto-relocates, so create a symlink so it finds its files
ln -s ../.. lib64/clang/$FULL_VERSION/lib64

# Move shared libraries to proper /usr/lib64
mv -t lib64/ lib/*.so lib/lib*.so.*

#/usr
popd
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib/clang/18/include/cuda_wrappers/algorithm
/usr/lib/clang/18/include/cuda_wrappers/cmath
/usr/lib/clang/18/include/cuda_wrappers/complex
/usr/lib/clang/18/include/cuda_wrappers/new
/usr/lib/clang/18/include/module.modulemap
/usr/lib/clang/18/include/openmp_wrappers/cmath
/usr/lib/clang/18/include/openmp_wrappers/complex
/usr/lib/clang/18/include/openmp_wrappers/new
/usr/lib/libear/__init__.py
/usr/lib/libear/config.h.in
/usr/lib/libear/ear.c
/usr/lib/libscanbuild/__init__.py
/usr/lib/libscanbuild/analyze.py
/usr/lib/libscanbuild/arguments.py
/usr/lib/libscanbuild/clang.py
/usr/lib/libscanbuild/compilation.py
/usr/lib/libscanbuild/intercept.py
/usr/lib/libscanbuild/report.py
/usr/lib/libscanbuild/resources/scanview.css
/usr/lib/libscanbuild/resources/selectable.js
/usr/lib/libscanbuild/resources/sorttable.js
/usr/lib/libscanbuild/shell.py
/usr/lib/libsycl-bfloat16.o
/usr/lib/libsycl-cmath-fp64.o
/usr/lib/libsycl-cmath.o
/usr/lib/libsycl-complex-fp64.o
/usr/lib/libsycl-complex.o
/usr/lib/libsycl-crt.o
/usr/lib/libsycl-fallback-bfloat16.o
/usr/lib/libsycl-fallback-bfloat16.spv
/usr/lib/libsycl-fallback-cassert.o
/usr/lib/libsycl-fallback-cassert.spv
/usr/lib/libsycl-fallback-cmath-fp64.o
/usr/lib/libsycl-fallback-cmath-fp64.spv
/usr/lib/libsycl-fallback-cmath.o
/usr/lib/libsycl-fallback-cmath.spv
/usr/lib/libsycl-fallback-complex-fp64.o
/usr/lib/libsycl-fallback-complex-fp64.spv
/usr/lib/libsycl-fallback-complex.o
/usr/lib/libsycl-fallback-complex.spv
/usr/lib/libsycl-fallback-cstring.o
/usr/lib/libsycl-fallback-cstring.spv
/usr/lib/libsycl-fallback-imf-bf16.o
/usr/lib/libsycl-fallback-imf-bf16.spv
/usr/lib/libsycl-fallback-imf-fp64.o
/usr/lib/libsycl-fallback-imf-fp64.spv
/usr/lib/libsycl-fallback-imf.o
/usr/lib/libsycl-fallback-imf.spv
/usr/lib/libsycl-imf-bf16.o
/usr/lib/libsycl-imf-fp64.o
/usr/lib/libsycl-imf.o
/usr/lib/libsycl-itt-compiler-wrappers.o
/usr/lib/libsycl-itt-stubs.o
/usr/lib/libsycl-itt-user-wrappers.o
/usr/lib/libsycl-native-bfloat16.o
/usr/lib/libsycl-native-bfloat16.spv
/usr/lib64/clang/dpcpp-2023.08.31/bin/amdgpu-arch
/usr/lib64/clang/dpcpp-2023.08.31/bin/analyze-build
/usr/lib64/clang/dpcpp-2023.08.31/bin/append-file
/usr/lib64/clang/dpcpp-2023.08.31/bin/bugpoint
/usr/lib64/clang/dpcpp-2023.08.31/bin/c-index-test
/usr/lib64/clang/dpcpp-2023.08.31/bin/clang
/usr/lib64/clang/dpcpp-2023.08.31/bin/clang++
/usr/lib64/clang/dpcpp-2023.08.31/bin/clang-18
/usr/lib64/clang/dpcpp-2023.08.31/bin/clang-check
/usr/lib64/clang/dpcpp-2023.08.31/bin/clang-cl
/usr/lib64/clang/dpcpp-2023.08.31/bin/clang-cpp
/usr/lib64/clang/dpcpp-2023.08.31/bin/clang-extdef-mapping
/usr/lib64/clang/dpcpp-2023.08.31/bin/clang-format
/usr/lib64/clang/dpcpp-2023.08.31/bin/clang-linker-wrapper
/usr/lib64/clang/dpcpp-2023.08.31/bin/clang-nvlink-wrapper
/usr/lib64/clang/dpcpp-2023.08.31/bin/clang-offload-bundler
/usr/lib64/clang/dpcpp-2023.08.31/bin/clang-offload-deps
/usr/lib64/clang/dpcpp-2023.08.31/bin/clang-offload-extract
/usr/lib64/clang/dpcpp-2023.08.31/bin/clang-offload-packager
/usr/lib64/clang/dpcpp-2023.08.31/bin/clang-offload-wrapper
/usr/lib64/clang/dpcpp-2023.08.31/bin/clang-refactor
/usr/lib64/clang/dpcpp-2023.08.31/bin/clang-rename
/usr/lib64/clang/dpcpp-2023.08.31/bin/clang-repl
/usr/lib64/clang/dpcpp-2023.08.31/bin/clang-scan-deps
/usr/lib64/clang/dpcpp-2023.08.31/bin/clang-tblgen
/usr/lib64/clang/dpcpp-2023.08.31/bin/cllayerinfo
/usr/lib64/clang/dpcpp-2023.08.31/bin/diagtool
/usr/lib64/clang/dpcpp-2023.08.31/bin/dsymutil
/usr/lib64/clang/dpcpp-2023.08.31/bin/file-table-tform
/usr/lib64/clang/dpcpp-2023.08.31/bin/git-clang-format
/usr/lib64/clang/dpcpp-2023.08.31/bin/hmaptool
/usr/lib64/clang/dpcpp-2023.08.31/bin/intercept-build
/usr/lib64/clang/dpcpp-2023.08.31/bin/llc
/usr/lib64/clang/dpcpp-2023.08.31/bin/lli
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-addr2line
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-ar
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-as
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-bcanalyzer
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-bitcode-strip
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-c-test
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-cat
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-cfi-verify
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-config
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-cov
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-cvtres
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-cxxdump
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-cxxfilt
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-cxxmap
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-debuginfo-analyzer
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-debuginfod
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-debuginfod-find
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-diff
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-dis
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-dlltool
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-dwarfdump
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-dwarfutil
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-dwp
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-exegesis
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-extract
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-foreach
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-gsymutil
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-ifs
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-install-name-tool
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-jitlink
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-lib
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-libtool-darwin
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-link
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-lipo
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-lto
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-lto2
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-mc
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-mca
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-ml
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-modextract
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-mt
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-nm
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-objcopy
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-objdump
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-opt-report
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-otool
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-pdbutil
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-profdata
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-profgen
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-ranlib
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-rc
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-readelf
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-readobj
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-readtapi
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-reduce
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-remarkutil
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-rtdyld
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-sim
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-size
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-spirv
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-split
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-stress
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-strings
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-strip
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-symbolizer
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-tblgen
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-tli-checker
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-undname
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-windres
/usr/lib64/clang/dpcpp-2023.08.31/bin/llvm-xray
/usr/lib64/clang/dpcpp-2023.08.31/bin/nvptx-arch
/usr/lib64/clang/dpcpp-2023.08.31/bin/opencl-aot
/usr/lib64/clang/dpcpp-2023.08.31/bin/opt
/usr/lib64/clang/dpcpp-2023.08.31/bin/sancov
/usr/lib64/clang/dpcpp-2023.08.31/bin/sanstats
/usr/lib64/clang/dpcpp-2023.08.31/bin/scan-build
/usr/lib64/clang/dpcpp-2023.08.31/bin/scan-build-py
/usr/lib64/clang/dpcpp-2023.08.31/bin/scan-view
/usr/lib64/clang/dpcpp-2023.08.31/bin/spirv-to-ir-wrapper
/usr/lib64/clang/dpcpp-2023.08.31/bin/sycl-ls
/usr/lib64/clang/dpcpp-2023.08.31/bin/sycl-post-link
/usr/lib64/clang/dpcpp-2023.08.31/bin/sycl-prof
/usr/lib64/clang/dpcpp-2023.08.31/bin/sycl-sanitize
/usr/lib64/clang/dpcpp-2023.08.31/bin/sycl-trace
/usr/lib64/clang/dpcpp-2023.08.31/bin/verify-uselistorder
/usr/lib64/clang/dpcpp-2023.08.31/lib64

%files bin
%defattr(-,root,root,-)
/usr/bin/amdgpu-arch-dpcpp
/usr/bin/analyze-build-dpcpp
/usr/bin/append-file-dpcpp
/usr/bin/bugpoint-dpcpp
/usr/bin/c-index-test-dpcpp
/usr/bin/clang++-dpcpp
/usr/bin/clang-18-dpcpp
/usr/bin/clang-check-dpcpp
/usr/bin/clang-cl-dpcpp
/usr/bin/clang-cpp-dpcpp
/usr/bin/clang-dpcpp
/usr/bin/clang-extdef-mapping-dpcpp
/usr/bin/clang-format-dpcpp
/usr/bin/clang-linker-wrapper-dpcpp
/usr/bin/clang-nvlink-wrapper-dpcpp
/usr/bin/clang-offload-bundler-dpcpp
/usr/bin/clang-offload-deps-dpcpp
/usr/bin/clang-offload-extract-dpcpp
/usr/bin/clang-offload-packager-dpcpp
/usr/bin/clang-offload-wrapper-dpcpp
/usr/bin/clang-refactor-dpcpp
/usr/bin/clang-rename-dpcpp
/usr/bin/clang-repl-dpcpp
/usr/bin/clang-scan-deps-dpcpp
/usr/bin/clang-tblgen-dpcpp
/usr/bin/cllayerinfo-dpcpp
/usr/bin/diagtool-dpcpp
/usr/bin/dsymutil-dpcpp
/usr/bin/file-table-tform-dpcpp
/usr/bin/git-clang-format-dpcpp
/usr/bin/hmaptool-dpcpp
/usr/bin/intercept-build-dpcpp
/usr/bin/llc-dpcpp
/usr/bin/lli-dpcpp
/usr/bin/llvm-addr2line-dpcpp
/usr/bin/llvm-ar-dpcpp
/usr/bin/llvm-as-dpcpp
/usr/bin/llvm-bcanalyzer-dpcpp
/usr/bin/llvm-bitcode-strip-dpcpp
/usr/bin/llvm-c-test-dpcpp
/usr/bin/llvm-cat-dpcpp
/usr/bin/llvm-cfi-verify-dpcpp
/usr/bin/llvm-config-dpcpp
/usr/bin/llvm-cov-dpcpp
/usr/bin/llvm-cvtres-dpcpp
/usr/bin/llvm-cxxdump-dpcpp
/usr/bin/llvm-cxxfilt-dpcpp
/usr/bin/llvm-cxxmap-dpcpp
/usr/bin/llvm-debuginfo-analyzer-dpcpp
/usr/bin/llvm-debuginfod-dpcpp
/usr/bin/llvm-debuginfod-find-dpcpp
/usr/bin/llvm-diff-dpcpp
/usr/bin/llvm-dis-dpcpp
/usr/bin/llvm-dlltool-dpcpp
/usr/bin/llvm-dwarfdump-dpcpp
/usr/bin/llvm-dwarfutil-dpcpp
/usr/bin/llvm-dwp-dpcpp
/usr/bin/llvm-exegesis-dpcpp
/usr/bin/llvm-extract-dpcpp
/usr/bin/llvm-foreach-dpcpp
/usr/bin/llvm-gsymutil-dpcpp
/usr/bin/llvm-ifs-dpcpp
/usr/bin/llvm-install-name-tool-dpcpp
/usr/bin/llvm-jitlink-dpcpp
/usr/bin/llvm-lib-dpcpp
/usr/bin/llvm-libtool-darwin-dpcpp
/usr/bin/llvm-link-dpcpp
/usr/bin/llvm-lipo-dpcpp
/usr/bin/llvm-lto-dpcpp
/usr/bin/llvm-lto2-dpcpp
/usr/bin/llvm-mc-dpcpp
/usr/bin/llvm-mca-dpcpp
/usr/bin/llvm-ml-dpcpp
/usr/bin/llvm-modextract-dpcpp
/usr/bin/llvm-mt-dpcpp
/usr/bin/llvm-nm-dpcpp
/usr/bin/llvm-objcopy-dpcpp
/usr/bin/llvm-objdump-dpcpp
/usr/bin/llvm-opt-report-dpcpp
/usr/bin/llvm-otool-dpcpp
/usr/bin/llvm-pdbutil-dpcpp
/usr/bin/llvm-profdata-dpcpp
/usr/bin/llvm-profgen-dpcpp
/usr/bin/llvm-ranlib-dpcpp
/usr/bin/llvm-rc-dpcpp
/usr/bin/llvm-readelf-dpcpp
/usr/bin/llvm-readobj-dpcpp
/usr/bin/llvm-readtapi-dpcpp
/usr/bin/llvm-reduce-dpcpp
/usr/bin/llvm-remarkutil-dpcpp
/usr/bin/llvm-rtdyld-dpcpp
/usr/bin/llvm-sim-dpcpp
/usr/bin/llvm-size-dpcpp
/usr/bin/llvm-spirv-dpcpp
/usr/bin/llvm-split-dpcpp
/usr/bin/llvm-stress-dpcpp
/usr/bin/llvm-strings-dpcpp
/usr/bin/llvm-strip-dpcpp
/usr/bin/llvm-symbolizer-dpcpp
/usr/bin/llvm-tblgen-dpcpp
/usr/bin/llvm-tli-checker-dpcpp
/usr/bin/llvm-undname-dpcpp
/usr/bin/llvm-windres-dpcpp
/usr/bin/llvm-xray-dpcpp
/usr/bin/nvptx-arch-dpcpp
/usr/bin/opencl-aot-dpcpp
/usr/bin/opt-dpcpp
/usr/bin/sancov-dpcpp
/usr/bin/sanstats-dpcpp
/usr/bin/scan-build-dpcpp
/usr/bin/scan-build-py-dpcpp
/usr/bin/scan-view-dpcpp
/usr/bin/spirv-to-ir-wrapper-dpcpp
/usr/bin/sycl-ls-dpcpp
/usr/bin/sycl-post-link-dpcpp
/usr/bin/sycl-prof-dpcpp
/usr/bin/sycl-sanitize-dpcpp
/usr/bin/sycl-trace-dpcpp
/usr/bin/verify-uselistorder-dpcpp

%files data
%defattr(-,root,root,-)
/usr/share/cmake/*

%files dev
%defattr(-,root,root,-)
/usr/include/llvm/SYCLLowerIR/CompileTimePropertiesPass.h
/usr/include/llvm/SYCLLowerIR/DeviceConfigFile.inc
/usr/include/llvm/SYCLLowerIR/DeviceConfigFile.td
/usr/include/llvm/SYCLLowerIR/DeviceGlobals.h
/usr/include/llvm/SYCLLowerIR/ESIMD/ESIMDUtils.h
/usr/include/llvm/SYCLLowerIR/ESIMD/ESIMDVerifier.h
/usr/include/llvm/SYCLLowerIR/ESIMD/LowerESIMD.h
/usr/include/llvm/SYCLLowerIR/GlobalOffset.h
/usr/include/llvm/SYCLLowerIR/HostPipes.h
/usr/include/llvm/SYCLLowerIR/LocalAccessorToSharedMemory.h
/usr/include/llvm/SYCLLowerIR/LowerInvokeSimd.h
/usr/include/llvm/SYCLLowerIR/LowerWGLocalMemory.h
/usr/include/llvm/SYCLLowerIR/LowerWGScope.h
/usr/include/llvm/SYCLLowerIR/MutatePrintfAddrspace.h
/usr/include/llvm/SYCLLowerIR/PrepareSYCLNativeCPU.h
/usr/include/llvm/SYCLLowerIR/RenameKernelSYCLNativeCPU.h
/usr/include/llvm/SYCLLowerIR/SYCLAddOptLevelAttribute.h
/usr/include/llvm/SYCLLowerIR/SYCLPropagateAspectsUsage.h
/usr/include/llvm/SYCLLowerIR/SYCLUtils.h
/usr/include/llvm/SYCLLowerIR/TargetHelpers.h
/usr/include/sycl/CL/__spirv/spirv_ops.hpp
/usr/include/sycl/CL/__spirv/spirv_types.hpp
/usr/include/sycl/CL/__spirv/spirv_vars.hpp
/usr/include/sycl/CL/cl.h
/usr/include/sycl/CL/cl_d3d10.h
/usr/include/sycl/CL/cl_d3d11.h
/usr/include/sycl/CL/cl_dx9_media_sharing.h
/usr/include/sycl/CL/cl_dx9_media_sharing_intel.h
/usr/include/sycl/CL/cl_egl.h
/usr/include/sycl/CL/cl_ext.h
/usr/include/sycl/CL/cl_ext_intel.h
/usr/include/sycl/CL/cl_gl.h
/usr/include/sycl/CL/cl_gl_ext.h
/usr/include/sycl/CL/cl_half.h
/usr/include/sycl/CL/cl_icd.h
/usr/include/sycl/CL/cl_layer.h
/usr/include/sycl/CL/cl_platform.h
/usr/include/sycl/CL/cl_va_api_media_sharing_intel.h
/usr/include/sycl/CL/cl_version.h
/usr/include/sycl/CL/opencl.h
/usr/include/sycl/CL/sycl.hpp
/usr/include/sycl/access/access.hpp
/usr/include/sycl/accessor.hpp
/usr/include/sycl/aliases.hpp
/usr/include/sycl/aspects.hpp
/usr/include/sycl/async_handler.hpp
/usr/include/sycl/atomic.hpp
/usr/include/sycl/atomic_fence.hpp
/usr/include/sycl/atomic_ref.hpp
/usr/include/sycl/backend.hpp
/usr/include/sycl/backend/cuda.hpp
/usr/include/sycl/backend/level_zero.hpp
/usr/include/sycl/backend/opencl.hpp
/usr/include/sycl/backend_types.hpp
/usr/include/sycl/bit_cast.hpp
/usr/include/sycl/buffer.hpp
/usr/include/sycl/builtins.hpp
/usr/include/sycl/builtins_esimd.hpp
/usr/include/sycl/builtins_marray_gen.hpp
/usr/include/sycl/builtins_scalar_gen.hpp
/usr/include/sycl/builtins_utils.hpp
/usr/include/sycl/builtins_vector_gen.hpp
/usr/include/sycl/context.hpp
/usr/include/sycl/define_vendors.hpp
/usr/include/sycl/detail/accessor_iterator.hpp
/usr/include/sycl/detail/aligned_allocator.hpp
/usr/include/sycl/detail/array.hpp
/usr/include/sycl/detail/assert_happened.hpp
/usr/include/sycl/detail/backend_traits.hpp
/usr/include/sycl/detail/backend_traits_cuda.hpp
/usr/include/sycl/detail/backend_traits_hip.hpp
/usr/include/sycl/detail/backend_traits_level_zero.hpp
/usr/include/sycl/detail/backend_traits_opencl.hpp
/usr/include/sycl/detail/boolean.hpp
/usr/include/sycl/detail/boost/README.txt
/usr/include/sycl/detail/boost/mp11.hpp
/usr/include/sycl/detail/boost/mp11/algorithm.hpp
/usr/include/sycl/detail/boost/mp11/bind.hpp
/usr/include/sycl/detail/boost/mp11/detail/config.hpp
/usr/include/sycl/detail/boost/mp11/detail/mp_append.hpp
/usr/include/sycl/detail/boost/mp11/detail/mp_copy_if.hpp
/usr/include/sycl/detail/boost/mp11/detail/mp_count.hpp
/usr/include/sycl/detail/boost/mp11/detail/mp_defer.hpp
/usr/include/sycl/detail/boost/mp11/detail/mp_fold.hpp
/usr/include/sycl/detail/boost/mp11/detail/mp_front.hpp
/usr/include/sycl/detail/boost/mp11/detail/mp_is_list.hpp
/usr/include/sycl/detail/boost/mp11/detail/mp_is_value_list.hpp
/usr/include/sycl/detail/boost/mp11/detail/mp_list.hpp
/usr/include/sycl/detail/boost/mp11/detail/mp_list_v.hpp
/usr/include/sycl/detail/boost/mp11/detail/mp_map_find.hpp
/usr/include/sycl/detail/boost/mp11/detail/mp_min_element.hpp
/usr/include/sycl/detail/boost/mp11/detail/mp_plus.hpp
/usr/include/sycl/detail/boost/mp11/detail/mp_remove_if.hpp
/usr/include/sycl/detail/boost/mp11/detail/mp_rename.hpp
/usr/include/sycl/detail/boost/mp11/detail/mp_value.hpp
/usr/include/sycl/detail/boost/mp11/detail/mp_void.hpp
/usr/include/sycl/detail/boost/mp11/detail/mp_with_index.hpp
/usr/include/sycl/detail/boost/mp11/detail/mpl_common.hpp
/usr/include/sycl/detail/boost/mp11/function.hpp
/usr/include/sycl/detail/boost/mp11/integer_sequence.hpp
/usr/include/sycl/detail/boost/mp11/integral.hpp
/usr/include/sycl/detail/boost/mp11/list.hpp
/usr/include/sycl/detail/boost/mp11/map.hpp
/usr/include/sycl/detail/boost/mp11/mpl.hpp
/usr/include/sycl/detail/boost/mp11/mpl_list.hpp
/usr/include/sycl/detail/boost/mp11/mpl_tuple.hpp
/usr/include/sycl/detail/boost/mp11/set.hpp
/usr/include/sycl/detail/boost/mp11/tuple.hpp
/usr/include/sycl/detail/boost/mp11/utility.hpp
/usr/include/sycl/detail/boost/mp11/version.hpp
/usr/include/sycl/detail/builtins.hpp
/usr/include/sycl/detail/cg.hpp
/usr/include/sycl/detail/cg_types.hpp
/usr/include/sycl/detail/cl.h
/usr/include/sycl/detail/common.hpp
/usr/include/sycl/detail/common_info.hpp
/usr/include/sycl/detail/cuda_definitions.hpp
/usr/include/sycl/detail/defines.hpp
/usr/include/sycl/detail/defines_elementary.hpp
/usr/include/sycl/detail/device_filter.hpp
/usr/include/sycl/detail/device_global_map.hpp
/usr/include/sycl/detail/export.hpp
/usr/include/sycl/detail/generic_type_lists.hpp
/usr/include/sycl/detail/generic_type_traits.hpp
/usr/include/sycl/detail/group_sort_impl.hpp
/usr/include/sycl/detail/handler_proxy.hpp
/usr/include/sycl/detail/helpers.hpp
/usr/include/sycl/detail/hip_definitions.hpp
/usr/include/sycl/detail/host_pipe_map.hpp
/usr/include/sycl/detail/host_profiling_info.hpp
/usr/include/sycl/detail/image_accessor_util.hpp
/usr/include/sycl/detail/image_ocl_types.hpp
/usr/include/sycl/detail/impl_utils.hpp
/usr/include/sycl/detail/info_desc_helpers.hpp
/usr/include/sycl/detail/iostream_proxy.hpp
/usr/include/sycl/detail/item_base.hpp
/usr/include/sycl/detail/kernel_desc.hpp
/usr/include/sycl/detail/kernel_properties.hpp
/usr/include/sycl/detail/locked.hpp
/usr/include/sycl/detail/memcpy.hpp
/usr/include/sycl/detail/native_cpu.hpp
/usr/include/sycl/detail/os_util.hpp
/usr/include/sycl/detail/owner_less_base.hpp
/usr/include/sycl/detail/pi.def
/usr/include/sycl/detail/pi.h
/usr/include/sycl/detail/pi.hpp
/usr/include/sycl/detail/pi_error.def
/usr/include/sycl/detail/properties_traits.def
/usr/include/sycl/detail/property_helper.hpp
/usr/include/sycl/detail/property_list_base.hpp
/usr/include/sycl/detail/reduction_forward.hpp
/usr/include/sycl/detail/spec_const_integration.hpp
/usr/include/sycl/detail/spinlock.hpp
/usr/include/sycl/detail/spirv.hpp
/usr/include/sycl/detail/stl_type_traits.hpp
/usr/include/sycl/detail/sycl_mem_obj_allocator.hpp
/usr/include/sycl/detail/tuple.hpp
/usr/include/sycl/detail/type_list.hpp
/usr/include/sycl/detail/type_traits.hpp
/usr/include/sycl/detail/usm_impl.hpp
/usr/include/sycl/detail/util.hpp
/usr/include/sycl/detail/vector_traits.hpp
/usr/include/sycl/device.hpp
/usr/include/sycl/device_aspect_macros.hpp
/usr/include/sycl/device_aspect_traits.hpp
/usr/include/sycl/device_event.hpp
/usr/include/sycl/device_selector.hpp
/usr/include/sycl/event.hpp
/usr/include/sycl/exception.hpp
/usr/include/sycl/exception_list.hpp
/usr/include/sycl/ext/codeplay/experimental/fusion_properties.hpp
/usr/include/sycl/ext/codeplay/experimental/fusion_wrapper.hpp
/usr/include/sycl/ext/intel/esimd.hpp
/usr/include/sycl/ext/intel/esimd/alt_ui.hpp
/usr/include/sycl/ext/intel/esimd/common.hpp
/usr/include/sycl/ext/intel/esimd/detail/atomic_intrin.hpp
/usr/include/sycl/ext/intel/esimd/detail/bfloat16_type_traits.hpp
/usr/include/sycl/ext/intel/esimd/detail/defines_elementary.hpp
/usr/include/sycl/ext/intel/esimd/detail/elem_type_traits.hpp
/usr/include/sycl/ext/intel/esimd/detail/half_type_traits.hpp
/usr/include/sycl/ext/intel/esimd/detail/host_util.hpp
/usr/include/sycl/ext/intel/esimd/detail/intrin.hpp
/usr/include/sycl/ext/intel/esimd/detail/math_intrin.hpp
/usr/include/sycl/ext/intel/esimd/detail/memory_intrin.hpp
/usr/include/sycl/ext/intel/esimd/detail/operators.hpp
/usr/include/sycl/ext/intel/esimd/detail/region.hpp
/usr/include/sycl/ext/intel/esimd/detail/simd_mask_impl.hpp
/usr/include/sycl/ext/intel/esimd/detail/simd_obj_impl.hpp
/usr/include/sycl/ext/intel/esimd/detail/simd_view_impl.hpp
/usr/include/sycl/ext/intel/esimd/detail/sycl_util.hpp
/usr/include/sycl/ext/intel/esimd/detail/test_proxy.hpp
/usr/include/sycl/ext/intel/esimd/detail/tfloat32_type_traits.hpp
/usr/include/sycl/ext/intel/esimd/detail/type_format.hpp
/usr/include/sycl/ext/intel/esimd/detail/types.hpp
/usr/include/sycl/ext/intel/esimd/detail/types_elementary.hpp
/usr/include/sycl/ext/intel/esimd/detail/util.hpp
/usr/include/sycl/ext/intel/esimd/emu/detail/esimd_emulator_device_interface.hpp
/usr/include/sycl/ext/intel/esimd/emu/detail/esimd_emulator_functions_v1.h
/usr/include/sycl/ext/intel/esimd/math.hpp
/usr/include/sycl/ext/intel/esimd/memory.hpp
/usr/include/sycl/ext/intel/esimd/native/common.hpp
/usr/include/sycl/ext/intel/esimd/simd.hpp
/usr/include/sycl/ext/intel/esimd/simd_view.hpp
/usr/include/sycl/ext/intel/esimd/xmx/common.hpp
/usr/include/sycl/ext/intel/esimd/xmx/dpas.hpp
/usr/include/sycl/ext/intel/experimental/detail/misc_intrin.hpp
/usr/include/sycl/ext/intel/experimental/esimd/common.hpp
/usr/include/sycl/ext/intel/experimental/esimd/detail/math_intrin.hpp
/usr/include/sycl/ext/intel/experimental/esimd/detail/memory_intrin.hpp
/usr/include/sycl/ext/intel/experimental/esimd/detail/util.hpp
/usr/include/sycl/ext/intel/experimental/esimd/math.hpp
/usr/include/sycl/ext/intel/experimental/esimd/memory.hpp
/usr/include/sycl/ext/intel/experimental/esimd/tfloat32.hpp
/usr/include/sycl/ext/intel/experimental/fpga_annotated_properties.hpp
/usr/include/sycl/ext/intel/experimental/fpga_kernel_properties.hpp
/usr/include/sycl/ext/intel/experimental/fpga_lsu.hpp
/usr/include/sycl/ext/intel/experimental/fpga_utils.hpp
/usr/include/sycl/ext/intel/experimental/grf_size_properties.hpp
/usr/include/sycl/ext/intel/experimental/kernel_execution_properties.hpp
/usr/include/sycl/ext/intel/experimental/online_compiler.hpp
/usr/include/sycl/ext/intel/experimental/pipe_properties.hpp
/usr/include/sycl/ext/intel/experimental/pipes.hpp
/usr/include/sycl/ext/intel/experimental/usm_properties.hpp
/usr/include/sycl/ext/intel/fpga_device_selector.hpp
/usr/include/sycl/ext/intel/fpga_dsp_control.hpp
/usr/include/sycl/ext/intel/fpga_extensions.hpp
/usr/include/sycl/ext/intel/fpga_loop_fuse.hpp
/usr/include/sycl/ext/intel/fpga_lsu.hpp
/usr/include/sycl/ext/intel/fpga_reg.hpp
/usr/include/sycl/ext/intel/fpga_utils.hpp
/usr/include/sycl/ext/intel/math.hpp
/usr/include/sycl/ext/intel/math/imf_fp_conversions.hpp
/usr/include/sycl/ext/intel/math/imf_half_trivial.hpp
/usr/include/sycl/ext/intel/math/imf_simd.hpp
/usr/include/sycl/ext/intel/online_compiler.hpp
/usr/include/sycl/ext/intel/pipes.hpp
/usr/include/sycl/ext/intel/usm_pointers.hpp
/usr/include/sycl/ext/oneapi/accessor_property_list.hpp
/usr/include/sycl/ext/oneapi/backend/hip.hpp
/usr/include/sycl/ext/oneapi/backend/level_zero.hpp
/usr/include/sycl/ext/oneapi/backend/level_zero_ownership.hpp
/usr/include/sycl/ext/oneapi/bf16_storage_builtins.hpp
/usr/include/sycl/ext/oneapi/bfloat16.hpp
/usr/include/sycl/ext/oneapi/bindless_images.hpp
/usr/include/sycl/ext/oneapi/bindless_images_descriptor.hpp
/usr/include/sycl/ext/oneapi/bindless_images_interop.hpp
/usr/include/sycl/ext/oneapi/bindless_images_memory.hpp
/usr/include/sycl/ext/oneapi/bindless_images_sampler.hpp
/usr/include/sycl/ext/oneapi/device_global/device_global.hpp
/usr/include/sycl/ext/oneapi/device_global/properties.hpp
/usr/include/sycl/ext/oneapi/dot_product.hpp
/usr/include/sycl/ext/oneapi/experimental/annotated_arg/annotated_arg.hpp
/usr/include/sycl/ext/oneapi/experimental/annotated_ptr/annotated_ptr.hpp
/usr/include/sycl/ext/oneapi/experimental/backend/backend_traits_cuda.hpp
/usr/include/sycl/ext/oneapi/experimental/backend/cuda.hpp
/usr/include/sycl/ext/oneapi/experimental/ballot_group.hpp
/usr/include/sycl/ext/oneapi/experimental/bfloat16_math.hpp
/usr/include/sycl/ext/oneapi/experimental/builtins.hpp
/usr/include/sycl/ext/oneapi/experimental/common_annotated_properties/properties.hpp
/usr/include/sycl/ext/oneapi/experimental/cuda/barrier.hpp
/usr/include/sycl/ext/oneapi/experimental/cuda/builtins.hpp
/usr/include/sycl/ext/oneapi/experimental/cuda/non_uniform_algorithms.hpp
/usr/include/sycl/ext/oneapi/experimental/detail/invoke_simd_types.hpp
/usr/include/sycl/ext/oneapi/experimental/device_architecture.hpp
/usr/include/sycl/ext/oneapi/experimental/fixed_size_group.hpp
/usr/include/sycl/ext/oneapi/experimental/graph.hpp
/usr/include/sycl/ext/oneapi/experimental/group_helpers_sorters.hpp
/usr/include/sycl/ext/oneapi/experimental/group_sort.hpp
/usr/include/sycl/ext/oneapi/experimental/invoke_simd.hpp
/usr/include/sycl/ext/oneapi/experimental/non_uniform_groups.hpp
/usr/include/sycl/ext/oneapi/experimental/opportunistic_group.hpp
/usr/include/sycl/ext/oneapi/experimental/root_group.hpp
/usr/include/sycl/ext/oneapi/experimental/sycl_complex.hpp
/usr/include/sycl/ext/oneapi/experimental/tangle_group.hpp
/usr/include/sycl/ext/oneapi/experimental/uniform.hpp
/usr/include/sycl/ext/oneapi/experimental/user_defined_reductions.hpp
/usr/include/sycl/ext/oneapi/filter_selector.hpp
/usr/include/sycl/ext/oneapi/functional.hpp
/usr/include/sycl/ext/oneapi/group_local_memory.hpp
/usr/include/sycl/ext/oneapi/kernel_properties/properties.hpp
/usr/include/sycl/ext/oneapi/latency_control/properties.hpp
/usr/include/sycl/ext/oneapi/matrix/matrix-intel.hpp
/usr/include/sycl/ext/oneapi/matrix/matrix-jit.hpp
/usr/include/sycl/ext/oneapi/matrix/matrix-tensorcores.hpp
/usr/include/sycl/ext/oneapi/matrix/matrix-unified-utils.hpp
/usr/include/sycl/ext/oneapi/matrix/matrix-unified.hpp
/usr/include/sycl/ext/oneapi/matrix/matrix.hpp
/usr/include/sycl/ext/oneapi/matrix/static-query-use.hpp
/usr/include/sycl/ext/oneapi/matrix/static-query.hpp
/usr/include/sycl/ext/oneapi/matrix/utils.hpp
/usr/include/sycl/ext/oneapi/owner_less.hpp
/usr/include/sycl/ext/oneapi/properties/properties.hpp
/usr/include/sycl/ext/oneapi/properties/property.hpp
/usr/include/sycl/ext/oneapi/properties/property_utils.hpp
/usr/include/sycl/ext/oneapi/properties/property_value.hpp
/usr/include/sycl/ext/oneapi/sub_group.hpp
/usr/include/sycl/ext/oneapi/sub_group_mask.hpp
/usr/include/sycl/ext/oneapi/weak_object.hpp
/usr/include/sycl/ext/oneapi/weak_object_base.hpp
/usr/include/sycl/feature_test.hpp
/usr/include/sycl/functional.hpp
/usr/include/sycl/group.hpp
/usr/include/sycl/group_algorithm.hpp
/usr/include/sycl/group_barrier.hpp
/usr/include/sycl/h_item.hpp
/usr/include/sycl/half_type.hpp
/usr/include/sycl/handler.hpp
/usr/include/sycl/id.hpp
/usr/include/sycl/image.hpp
/usr/include/sycl/info/aspects.def
/usr/include/sycl/info/aspects_deprecated.def
/usr/include/sycl/info/context_traits.def
/usr/include/sycl/info/device_traits.def
/usr/include/sycl/info/device_traits_deprecated.def
/usr/include/sycl/info/event_profiling_traits.def
/usr/include/sycl/info/event_traits.def
/usr/include/sycl/info/ext_codeplay_device_traits.def
/usr/include/sycl/info/ext_intel_device_traits.def
/usr/include/sycl/info/ext_oneapi_device_traits.def
/usr/include/sycl/info/info_desc.hpp
/usr/include/sycl/info/kernel_device_specific_traits.def
/usr/include/sycl/info/kernel_traits.def
/usr/include/sycl/info/platform_traits.def
/usr/include/sycl/info/queue_traits.def
/usr/include/sycl/interop_handle.hpp
/usr/include/sycl/item.hpp
/usr/include/sycl/kernel.hpp
/usr/include/sycl/kernel_bundle.hpp
/usr/include/sycl/kernel_bundle_enums.hpp
/usr/include/sycl/kernel_handler.hpp
/usr/include/sycl/known_identity.hpp
/usr/include/sycl/marray.hpp
/usr/include/sycl/memory_enums.hpp
/usr/include/sycl/multi_ptr.hpp
/usr/include/sycl/nd_item.hpp
/usr/include/sycl/nd_range.hpp
/usr/include/sycl/pipes.hpp
/usr/include/sycl/platform.hpp
/usr/include/sycl/pointers.hpp
/usr/include/sycl/properties/accessor_properties.hpp
/usr/include/sycl/properties/all_properties.hpp
/usr/include/sycl/properties/buffer_properties.hpp
/usr/include/sycl/properties/context_properties.hpp
/usr/include/sycl/properties/image_properties.hpp
/usr/include/sycl/properties/property_traits.hpp
/usr/include/sycl/properties/queue_properties.def
/usr/include/sycl/properties/queue_properties.hpp
/usr/include/sycl/properties/reduction_properties.hpp
/usr/include/sycl/property_list.hpp
/usr/include/sycl/property_list_conversion.hpp
/usr/include/sycl/queue.hpp
/usr/include/sycl/range.hpp
/usr/include/sycl/reduction.hpp
/usr/include/sycl/sampler.hpp
/usr/include/sycl/specialization_id.hpp
/usr/include/sycl/stl.hpp
/usr/include/sycl/stream.hpp
/usr/include/sycl/sub_group.hpp
/usr/include/sycl/swizzles.def
/usr/include/sycl/sycl.hpp
/usr/include/sycl/sycl_span.hpp
/usr/include/sycl/types.hpp
/usr/include/sycl/usm.hpp
/usr/include/sycl/usm/usm_allocator.hpp
/usr/include/sycl/usm/usm_enums.hpp
/usr/include/sycl/usm/usm_pointer_info.hpp
/usr/include/sycl/version.hpp
/usr/include/syclcompat.hpp
/usr/include/syclcompat/defs.hpp
/usr/include/syclcompat/device.hpp
/usr/include/syclcompat/dims.hpp
/usr/include/syclcompat/kernel.hpp
/usr/include/syclcompat/memory.hpp
/usr/include/syclcompat/syclcompat.hpp
/usr/lib/clang/18/include/__clang_cuda_builtin_vars.h
/usr/lib/clang/18/include/__clang_cuda_cmath.h
/usr/lib/clang/18/include/__clang_cuda_complex_builtins.h
/usr/lib/clang/18/include/__clang_cuda_device_functions.h
/usr/lib/clang/18/include/__clang_cuda_intrinsics.h
/usr/lib/clang/18/include/__clang_cuda_libdevice_declares.h
/usr/lib/clang/18/include/__clang_cuda_math.h
/usr/lib/clang/18/include/__clang_cuda_math_forward_declares.h
/usr/lib/clang/18/include/__clang_cuda_runtime_wrapper.h
/usr/lib/clang/18/include/__clang_cuda_texture_intrinsics.h
/usr/lib/clang/18/include/__clang_hip_cmath.h
/usr/lib/clang/18/include/__clang_hip_libdevice_declares.h
/usr/lib/clang/18/include/__clang_hip_math.h
/usr/lib/clang/18/include/__clang_hip_runtime_wrapper.h
/usr/lib/clang/18/include/__clang_hip_stdlib.h
/usr/lib/clang/18/include/__stddef_max_align_t.h
/usr/lib/clang/18/include/__wmmintrin_aes.h
/usr/lib/clang/18/include/__wmmintrin_pclmul.h
/usr/lib/clang/18/include/adxintrin.h
/usr/lib/clang/18/include/altivec.h
/usr/lib/clang/18/include/ammintrin.h
/usr/lib/clang/18/include/amxcomplexintrin.h
/usr/lib/clang/18/include/amxfp16intrin.h
/usr/lib/clang/18/include/amxintrin.h
/usr/lib/clang/18/include/arm64intr.h
/usr/lib/clang/18/include/arm_acle.h
/usr/lib/clang/18/include/arm_cmse.h
/usr/lib/clang/18/include/arm_neon_sve_bridge.h
/usr/lib/clang/18/include/armintr.h
/usr/lib/clang/18/include/avx2intrin.h
/usr/lib/clang/18/include/avx512bf16intrin.h
/usr/lib/clang/18/include/avx512bitalgintrin.h
/usr/lib/clang/18/include/avx512bwintrin.h
/usr/lib/clang/18/include/avx512cdintrin.h
/usr/lib/clang/18/include/avx512dqintrin.h
/usr/lib/clang/18/include/avx512erintrin.h
/usr/lib/clang/18/include/avx512fintrin.h
/usr/lib/clang/18/include/avx512fp16intrin.h
/usr/lib/clang/18/include/avx512ifmaintrin.h
/usr/lib/clang/18/include/avx512ifmavlintrin.h
/usr/lib/clang/18/include/avx512pfintrin.h
/usr/lib/clang/18/include/avx512vbmi2intrin.h
/usr/lib/clang/18/include/avx512vbmiintrin.h
/usr/lib/clang/18/include/avx512vbmivlintrin.h
/usr/lib/clang/18/include/avx512vlbf16intrin.h
/usr/lib/clang/18/include/avx512vlbitalgintrin.h
/usr/lib/clang/18/include/avx512vlbwintrin.h
/usr/lib/clang/18/include/avx512vlcdintrin.h
/usr/lib/clang/18/include/avx512vldqintrin.h
/usr/lib/clang/18/include/avx512vlfp16intrin.h
/usr/lib/clang/18/include/avx512vlintrin.h
/usr/lib/clang/18/include/avx512vlvbmi2intrin.h
/usr/lib/clang/18/include/avx512vlvnniintrin.h
/usr/lib/clang/18/include/avx512vlvp2intersectintrin.h
/usr/lib/clang/18/include/avx512vnniintrin.h
/usr/lib/clang/18/include/avx512vp2intersectintrin.h
/usr/lib/clang/18/include/avx512vpopcntdqintrin.h
/usr/lib/clang/18/include/avx512vpopcntdqvlintrin.h
/usr/lib/clang/18/include/avxifmaintrin.h
/usr/lib/clang/18/include/avxintrin.h
/usr/lib/clang/18/include/avxneconvertintrin.h
/usr/lib/clang/18/include/avxvnniint16intrin.h
/usr/lib/clang/18/include/avxvnniint8intrin.h
/usr/lib/clang/18/include/avxvnniintrin.h
/usr/lib/clang/18/include/bmi2intrin.h
/usr/lib/clang/18/include/bmiintrin.h
/usr/lib/clang/18/include/builtins.h
/usr/lib/clang/18/include/cet.h
/usr/lib/clang/18/include/cetintrin.h
/usr/lib/clang/18/include/cldemoteintrin.h
/usr/lib/clang/18/include/clflushoptintrin.h
/usr/lib/clang/18/include/clwbintrin.h
/usr/lib/clang/18/include/clzerointrin.h
/usr/lib/clang/18/include/cmpccxaddintrin.h
/usr/lib/clang/18/include/cpuid.h
/usr/lib/clang/18/include/crc32intrin.h
/usr/lib/clang/18/include/cuda_wrappers/bits/shared_ptr_base.h
/usr/lib/clang/18/include/emmintrin.h
/usr/lib/clang/18/include/enqcmdintrin.h
/usr/lib/clang/18/include/f16cintrin.h
/usr/lib/clang/18/include/float.h
/usr/lib/clang/18/include/fma4intrin.h
/usr/lib/clang/18/include/fmaintrin.h
/usr/lib/clang/18/include/fxsrintrin.h
/usr/lib/clang/18/include/gfniintrin.h
/usr/lib/clang/18/include/hexagon_circ_brev_intrinsics.h
/usr/lib/clang/18/include/hexagon_protos.h
/usr/lib/clang/18/include/hexagon_types.h
/usr/lib/clang/18/include/hresetintrin.h
/usr/lib/clang/18/include/htmintrin.h
/usr/lib/clang/18/include/htmxlintrin.h
/usr/lib/clang/18/include/hvx_hexagon_protos.h
/usr/lib/clang/18/include/ia32intrin.h
/usr/lib/clang/18/include/immintrin.h
/usr/lib/clang/18/include/intrin.h
/usr/lib/clang/18/include/inttypes.h
/usr/lib/clang/18/include/invpcidintrin.h
/usr/lib/clang/18/include/iso646.h
/usr/lib/clang/18/include/keylockerintrin.h
/usr/lib/clang/18/include/larchintrin.h
/usr/lib/clang/18/include/limits.h
/usr/lib/clang/18/include/llvm_libc_wrappers/ctype.h
/usr/lib/clang/18/include/llvm_libc_wrappers/inttypes.h
/usr/lib/clang/18/include/llvm_libc_wrappers/stdio.h
/usr/lib/clang/18/include/llvm_libc_wrappers/stdlib.h
/usr/lib/clang/18/include/llvm_libc_wrappers/string.h
/usr/lib/clang/18/include/lwpintrin.h
/usr/lib/clang/18/include/lzcntintrin.h
/usr/lib/clang/18/include/mm3dnow.h
/usr/lib/clang/18/include/mm_malloc.h
/usr/lib/clang/18/include/mmintrin.h
/usr/lib/clang/18/include/movdirintrin.h
/usr/lib/clang/18/include/msa.h
/usr/lib/clang/18/include/mwaitxintrin.h
/usr/lib/clang/18/include/nmmintrin.h
/usr/lib/clang/18/include/opencl-c-base.h
/usr/lib/clang/18/include/opencl-c.h
/usr/lib/clang/18/include/openmp_wrappers/__clang_openmp_device_functions.h
/usr/lib/clang/18/include/openmp_wrappers/complex.h
/usr/lib/clang/18/include/openmp_wrappers/complex_cmath.h
/usr/lib/clang/18/include/openmp_wrappers/math.h
/usr/lib/clang/18/include/pconfigintrin.h
/usr/lib/clang/18/include/pkuintrin.h
/usr/lib/clang/18/include/pmmintrin.h
/usr/lib/clang/18/include/popcntintrin.h
/usr/lib/clang/18/include/ppc_wrappers/bmi2intrin.h
/usr/lib/clang/18/include/ppc_wrappers/bmiintrin.h
/usr/lib/clang/18/include/ppc_wrappers/emmintrin.h
/usr/lib/clang/18/include/ppc_wrappers/immintrin.h
/usr/lib/clang/18/include/ppc_wrappers/mm_malloc.h
/usr/lib/clang/18/include/ppc_wrappers/mmintrin.h
/usr/lib/clang/18/include/ppc_wrappers/pmmintrin.h
/usr/lib/clang/18/include/ppc_wrappers/smmintrin.h
/usr/lib/clang/18/include/ppc_wrappers/tmmintrin.h
/usr/lib/clang/18/include/ppc_wrappers/x86gprintrin.h
/usr/lib/clang/18/include/ppc_wrappers/x86intrin.h
/usr/lib/clang/18/include/ppc_wrappers/xmmintrin.h
/usr/lib/clang/18/include/prfchiintrin.h
/usr/lib/clang/18/include/prfchwintrin.h
/usr/lib/clang/18/include/ptwriteintrin.h
/usr/lib/clang/18/include/raointintrin.h
/usr/lib/clang/18/include/rdpruintrin.h
/usr/lib/clang/18/include/rdseedintrin.h
/usr/lib/clang/18/include/riscv_ntlh.h
/usr/lib/clang/18/include/rtmintrin.h
/usr/lib/clang/18/include/s390intrin.h
/usr/lib/clang/18/include/serializeintrin.h
/usr/lib/clang/18/include/sgxintrin.h
/usr/lib/clang/18/include/sha512intrin.h
/usr/lib/clang/18/include/shaintrin.h
/usr/lib/clang/18/include/sifive_vector.h
/usr/lib/clang/18/include/sm3intrin.h
/usr/lib/clang/18/include/sm4intrin.h
/usr/lib/clang/18/include/smmintrin.h
/usr/lib/clang/18/include/stdalign.h
/usr/lib/clang/18/include/stdarg.h
/usr/lib/clang/18/include/stdatomic.h
/usr/lib/clang/18/include/stdbool.h
/usr/lib/clang/18/include/stddef.h
/usr/lib/clang/18/include/stdint.h
/usr/lib/clang/18/include/stdnoreturn.h
/usr/lib/clang/18/include/tbmintrin.h
/usr/lib/clang/18/include/tgmath.h
/usr/lib/clang/18/include/tmmintrin.h
/usr/lib/clang/18/include/tsxldtrkintrin.h
/usr/lib/clang/18/include/uintrintrin.h
/usr/lib/clang/18/include/unwind.h
/usr/lib/clang/18/include/vadefs.h
/usr/lib/clang/18/include/vaesintrin.h
/usr/lib/clang/18/include/varargs.h
/usr/lib/clang/18/include/vecintrin.h
/usr/lib/clang/18/include/velintrin.h
/usr/lib/clang/18/include/velintrin_approx.h
/usr/lib/clang/18/include/velintrin_gen.h
/usr/lib/clang/18/include/vpclmulqdqintrin.h
/usr/lib/clang/18/include/waitpkgintrin.h
/usr/lib/clang/18/include/wasm_simd128.h
/usr/lib/clang/18/include/wbnoinvdintrin.h
/usr/lib/clang/18/include/wmmintrin.h
/usr/lib/clang/18/include/x86gprintrin.h
/usr/lib/clang/18/include/x86intrin.h
/usr/lib/clang/18/include/xmmintrin.h
/usr/lib/clang/18/include/xopintrin.h
/usr/lib/clang/18/include/xsavecintrin.h
/usr/lib/clang/18/include/xsaveintrin.h
/usr/lib/clang/18/include/xsaveoptintrin.h
/usr/lib/clang/18/include/xsavesintrin.h
/usr/lib/clang/18/include/xtestintrin.h
/usr/lib/cmake/clang/AddClang.cmake
/usr/lib/cmake/clang/ClangConfig.cmake
/usr/lib/cmake/clang/ClangConfigVersion.cmake
/usr/lib/cmake/clang/ClangTargets-relwithdebinfo.cmake
/usr/lib/cmake/clang/ClangTargets.cmake
/usr/lib/cmake/llvm/AddLLVM.cmake
/usr/lib/cmake/llvm/AddOCaml.cmake
/usr/lib/cmake/llvm/AddSecurityFlags.cmake
/usr/lib/cmake/llvm/AddSphinxTarget.cmake
/usr/lib/cmake/llvm/CheckAtomic.cmake
/usr/lib/cmake/llvm/CheckCompilerVersion.cmake
/usr/lib/cmake/llvm/CheckProblematicConfigurations.cmake
/usr/lib/cmake/llvm/ChooseMSVCCRT.cmake
/usr/lib/cmake/llvm/CoverageReport.cmake
/usr/lib/cmake/llvm/CrossCompile.cmake
/usr/lib/cmake/llvm/DetermineGCCCompatible.cmake
/usr/lib/cmake/llvm/FindFFI.cmake
/usr/lib/cmake/llvm/FindLibEdit.cmake
/usr/lib/cmake/llvm/FindLibpfm.cmake
/usr/lib/cmake/llvm/FindOCaml.cmake
/usr/lib/cmake/llvm/FindSphinx.cmake
/usr/lib/cmake/llvm/FindTerminfo.cmake
/usr/lib/cmake/llvm/FindZ3.cmake
/usr/lib/cmake/llvm/Findzstd.cmake
/usr/lib/cmake/llvm/GenerateVersionFromVCS.cmake
/usr/lib/cmake/llvm/GetErrcMessages.cmake
/usr/lib/cmake/llvm/GetLibraryName.cmake
/usr/lib/cmake/llvm/HandleLLVMOptions.cmake
/usr/lib/cmake/llvm/HandleLLVMStdlib.cmake
/usr/lib/cmake/llvm/LLVM-Build.cmake
/usr/lib/cmake/llvm/LLVM-Config.cmake
/usr/lib/cmake/llvm/LLVMCheckLinkerFlag.cmake
/usr/lib/cmake/llvm/LLVMConfig.cmake
/usr/lib/cmake/llvm/LLVMConfigExtensions.cmake
/usr/lib/cmake/llvm/LLVMConfigVersion.cmake
/usr/lib/cmake/llvm/LLVMDistributionSupport.cmake
/usr/lib/cmake/llvm/LLVMExports-relwithdebinfo.cmake
/usr/lib/cmake/llvm/LLVMExports.cmake
/usr/lib/cmake/llvm/LLVMExternalProjectUtils.cmake
/usr/lib/cmake/llvm/LLVMInstallSymlink.cmake
/usr/lib/cmake/llvm/LLVMProcessSources.cmake
/usr/lib/cmake/llvm/SetTargetTriple.cmake
/usr/lib/cmake/llvm/TableGen.cmake
/usr/lib/cmake/llvm/TensorFlowCompile.cmake
/usr/lib/cmake/llvm/UseLibtool.cmake
/usr/lib/cmake/llvm/VersionFromVCS.cmake
/usr/lib/cmake/llvm/llvm-driver-template.cpp.in
/usr/lib/cmake/unified-runtime/unified-runtime-config-version.cmake
/usr/lib/cmake/unified-runtime/unified-runtime-config.cmake
/usr/lib/cmake/unified-runtime/unified-runtime-targets-relwithdebinfo.cmake
/usr/lib/cmake/unified-runtime/unified-runtime-targets.cmake
/usr/lib64/SYCLKernelFusion.so
/usr/lib64/libpi_level_zero.so
/usr/lib64/libpi_opencl.so
/usr/lib64/libpi_unified_runtime.so
/usr/lib64/libsycl.so
/usr/lib64/libsycl_pi_trace_collector.so
/usr/lib64/libsycl_profiler_collector.so
/usr/lib64/libsycl_sanitizer_collector.so
/usr/lib64/libur_adapter_level_zero.so
/usr/lib64/libur_loader.so
/usr/lib64/libxptifw.so
/usr/lib64/libze_trace_collector.so
/usr/lib64/pkgconfig/libur_loader.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libLTO.so.18-dpcpp
/usr/lib64/libRemarks.so.18-dpcpp
/usr/lib64/libclang-cpp.so.18-dpcpp
/usr/lib64/libclang.so.18-dpcpp
/usr/lib64/libclang.so.18.0.0-dpcpp
/usr/lib64/libsycl.so.7
/usr/lib64/libsycl.so.7.0.0-8
/usr/lib64/libsycl.so.7.0.0-8-gdb.py
/usr/lib64/libur_adapter_level_zero.so.0
/usr/lib64/libur_adapter_level_zero.so.0.0.0
/usr/lib64/libur_loader.so.0
/usr/lib64/libur_loader.so.0.7.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/dpcpp-compiler/11156021d878bfcbdf2563b4f65db32b4d9f92a3
/usr/share/package-licenses/dpcpp-compiler/2858f1aaa0df159c19da9047793c176ded5fde73
/usr/share/package-licenses/dpcpp-compiler/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/dpcpp-compiler/385649e7c18da3a07cfbd6679eebd0bca1c698c9
/usr/share/package-licenses/dpcpp-compiler/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
/usr/share/package-licenses/dpcpp-compiler/45c2429b5881295597e96c81fc50f7b8a42e769f
/usr/share/package-licenses/dpcpp-compiler/59a8ba331dede4d94bd654ac645e8d27463662f4
/usr/share/package-licenses/dpcpp-compiler/5a2314153eadadc69258a9429104cd11804ea304
/usr/share/package-licenses/dpcpp-compiler/5a64e4783751612e7603131e11bb81655bcb2b4e
/usr/share/package-licenses/dpcpp-compiler/5a99e7077ee89ba92fb3f584855e8970096cd5dc
/usr/share/package-licenses/dpcpp-compiler/5feeec1755c1a12a9ade79c0db7ce0dd05baf119
/usr/share/package-licenses/dpcpp-compiler/5ffa2266f82fe7453a84cc81e06ef01fa4b451d5
/usr/share/package-licenses/dpcpp-compiler/6b655b0685aa7ee33fa1e02103b3bf22ed06e099
/usr/share/package-licenses/dpcpp-compiler/723eea2469244a92b3e3461b79c3e848ce058cc6
/usr/share/package-licenses/dpcpp-compiler/72c865be698cefc46549ed61e279f98432364fca
/usr/share/package-licenses/dpcpp-compiler/7b75a5471af8b3d49e60df0a5d72f95ea8214231
/usr/share/package-licenses/dpcpp-compiler/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/dpcpp-compiler/85c0f2884378413881b4d3e27fc24b220f71889b
/usr/share/package-licenses/dpcpp-compiler/8737af83de0d40386dca9a4abe2b6faa83cb4750
/usr/share/package-licenses/dpcpp-compiler/8af372ad1edbed2cfaf0e79d25f7136ec6e55b47
/usr/share/package-licenses/dpcpp-compiler/8d3b142938f83e7045951089b52676a5605eee37
/usr/share/package-licenses/dpcpp-compiler/8f178caf2a2d6e6c711a30da69077572df356cf6
/usr/share/package-licenses/dpcpp-compiler/a1691103171dc1d21cfa85f1d4809a16b9f1367f
/usr/share/package-licenses/dpcpp-compiler/af07f365643f841c69797e9059b66f0bd847f1cd
/usr/share/package-licenses/dpcpp-compiler/b5d4ab4d1191e592c03310adfbe90d99a46bf9d7
/usr/share/package-licenses/dpcpp-compiler/bfc2b026231b7aca6db90de3471e76dbb94e9c24
/usr/share/package-licenses/dpcpp-compiler/c01c212bdf3925189f673e2081b44094023860ea
/usr/share/package-licenses/dpcpp-compiler/d79062af10a33188d4a74d976323845a2cf9023d
/usr/share/package-licenses/dpcpp-compiler/db1f866b29c6a191752c7c5924b7572cdbc47c34
/usr/share/package-licenses/dpcpp-compiler/e3cccabb67bd491a643d32a7d2b65b49836e626d
/usr/share/package-licenses/dpcpp-compiler/f4359b9da55a3b9e4d9513eb79cacf125fb49e7b
